"""
Service for rendering Interpretation Reports to HTML and PDF.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from PyQt6.QtGui import QTextDocument, QPageLayout, QPageSize
from PyQt6.QtPrintSupport import QPrinter
from PyQt6.QtCore import QSizeF

from ..models.interpretation_models import InterpretationReport

logger = logging.getLogger(__name__)

class ReportService:
    """
    Renders InterpretationReport objects into HTML or PDF using Qt.
    """
    
    # Simple CSS for the Visual Liturgy on paper
    STYLE_CSS = """
    body { font-family: 'Georgia', serif; color: #111; line-height: 1.6; }
    h1 { color: #222; border-bottom: 2px solid #444; padding-bottom: 10px; margin-top: 40px; }
    h2 { color: #333; margin-top: 25px; border-left: 4px solid #888; padding-left: 10px; }
    .meta { color: #666; font-style: italic; font-size: 0.9em; margin-bottom: 30px; }
    .archetype { font-weight: bold; color: #552200; }
    .essence { font-weight: bold; color: #003366; }
    .shadow { font-weight: bold; color: #660000; }
    .gift { font-weight: bold; color: #004400; }
    """

    def render_html(self, report: InterpretationReport) -> str:
        """Convert report to a full HTML string."""
        segments_html = []
        
        for seg in report.segments:
            c = seg.content
            
            blocks = []
            if c.archetype:
                blocks.append(f"<p><span class='archetype'>Archetype:</span> {c.archetype}</p>")
            
            # Main text (convert newlines to paragraphs ideally, but simple replace for now)
            text_html = f"<p>{c.text.replace(chr(10), '<br>')}</p>"
            blocks.append(text_html)
            
            if c.essence:
                blocks.append(f"<p><span class='essence'>Essence:</span> {c.essence}</p>")
            if c.shadow:
                blocks.append(f"<p><span class='shadow'>Shadow:</span> {c.shadow}</p>")
            if c.gift:
                blocks.append(f"<p><span class='gift'>Gift:</span> {c.gift}</p>")
                
            segment_body = "".join(blocks)
            segments_html.append(f"""
            <div class='segment'>
                <h2>{seg.title}</h2>
                {segment_body}
            </div>
            """)
            
        full_html = f"""
        <html>
        <head>
            <style>{self.STYLE_CSS}</style>
        </head>
        <body>
            <h1>{report.chart_name}</h1>
            <div class='meta'>Generated by IsopGem</div>
            {"".join(segments_html)}
        </body>
        </html>
        """
        return full_html

    def export_pdf(self, report: InterpretationReport, output_path: str) -> bool:
        """
        Render report to PDF at output_path.
        Requires QApplication to be running (usually true if UI is up).
        """
        try:
            html = self.render_html(report)
            
            document = QTextDocument()
            document.setHtml(html)
            
            printer = QPrinter(QPrinter.PrinterMode.HighResolution)
            printer.setOutputFormat(QPrinter.OutputFormat.PdfFormat)
            printer.setOutputFileName(output_path)
            printer.setPageSize(QPageSize(QPageSize.PageSizeId.A4))
            
            # Simple margin
            layout = QPageLayout()
            layout.setMode(QPageLayout.Mode.StandardMode)
            printer.setPageLayout(layout)
            
            document.print(printer)
            logger.info(f"PDF exported to {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to export PDF: {e}")
            return False
