"""Geometry services module."""
from .base_shape import GeometricShape, ShapeProperty
from .annulus_shape import AnnulusShape
from .circle_shape import CircleShape
from .crescent_shape import CrescentShape
from .ellipse_shape import EllipseShape
from .rose_curve_shape import RoseCurveShape
from .square_shape import SquareShape, RectangleShape
from .quadrilateral_shape import (
    ParallelogramShape,
    RhombusShape,
    TrapezoidShape,
    IsoscelesTrapezoidShape,
    KiteShape,
    DeltoidShape,
    CyclicQuadrilateralShape,
    TangentialQuadrilateralShape,
    BicentricQuadrilateralShape,
    QuadrilateralSolverShape,
)
from .triangle_shape import (
    EquilateralTriangleShape,
    RightTriangleShape,
    IsoscelesTriangleShape,
    ScaleneTriangleShape,
    AcuteTriangleShape,
    ObtuseTriangleShape,
    HeronianTriangleShape,
    IsoscelesRightTriangleShape,
    ThirtySixtyNinetyTriangleShape,
    GoldenTriangleShape,
    TriangleSolverShape,
)
from .vault_of_hestia_shape import VaultOfHestiaShape
from .polygon_shape import RegularPolygonShape
from .vesica_piscis_shape import VesicaPiscisShape
from .polygonal_numbers import (
    Point,
    polygonal_number_value,
    centered_polygonal_value,
    polygonal_number_points,
    polygonal_outline_points,
    star_number_value,
    generalized_star_number_value,
    generalized_star_number_points,
    star_number_points,
    max_radius,
)
from .tetrahedron_solid import TetrahedronSolidService, TetrahedronSolidCalculator
from .cube_solid import CubeSolidService, CubeSolidCalculator
from .octahedron_solid import OctahedronSolidService, OctahedronSolidCalculator
from .dodecahedron_solid import DodecahedronSolidService, DodecahedronSolidCalculator
from .icosahedron_solid import IcosahedronSolidService, IcosahedronSolidCalculator
from .tesseract_solid import TesseractSolidService, TesseractSolidCalculator
from .square_pyramid_solid import SquarePyramidSolidService, SquarePyramidSolidCalculator
from .square_pyramid_frustum_solid import (
    SquarePyramidFrustumSolidService,
    SquarePyramidFrustumSolidCalculator,
)
from .regular_pyramid_frustum_solids import (
    PentagonalPyramidFrustumSolidService,
    PentagonalPyramidFrustumSolidCalculator,
    HexagonalPyramidFrustumSolidService,
    HexagonalPyramidFrustumSolidCalculator,
)
from .rectangular_pyramid_solid import RectangularPyramidSolidService, RectangularPyramidSolidCalculator
from .rectangular_prism_solid import RectangularPrismSolidService, RectangularPrismSolidCalculator
from .regular_pyramid_solids import (
    TriangularPyramidSolidService,
    TriangularPyramidSolidCalculator,
    PentagonalPyramidSolidService,
    PentagonalPyramidSolidCalculator,
    HexagonalPyramidSolidService,
    HexagonalPyramidSolidCalculator,
    HeptagonalPyramidSolidService,
    HeptagonalPyramidSolidCalculator,
)
from .golden_pyramid_solid import GoldenPyramidSolidService, GoldenPyramidSolidCalculator
from .step_pyramid_solid import StepPyramidSolidService, StepPyramidSolidCalculator
from .regular_prism_solids import (
    RegularPrismSolidServiceBase,
    RegularPrismSolidCalculatorBase,
    TriangularPrismSolidService,
    TriangularPrismSolidCalculator,
    PentagonalPrismSolidService,
    PentagonalPrismSolidCalculator,
    HexagonalPrismSolidService,
    HexagonalPrismSolidCalculator,
    OctagonalPrismSolidService,
    OctagonalPrismSolidCalculator,
    HeptagonalPrismSolidService,
    HeptagonalPrismSolidCalculator,
)
from .oblique_prism_solid import ObliquePrismSolidService, ObliquePrismSolidCalculator
from .prismatic_frustum_solid import PrismaticFrustumSolidService, PrismaticFrustumSolidCalculator
from .regular_antiprism_solids import (
    RegularAntiprismSolidServiceBase,
    RegularAntiprismSolidCalculatorBase,
    TriangularAntiprismSolidService,
    TriangularAntiprismSolidCalculator,
    SquareAntiprismSolidService,
    SquareAntiprismSolidCalculator,
    PentagonalAntiprismSolidService,
    PentagonalAntiprismSolidCalculator,
    HexagonalAntiprismSolidService,
    HexagonalAntiprismSolidCalculator,
    OctagonalAntiprismSolidService,
    OctagonalAntiprismSolidCalculator,
    HeptagonalAntiprismSolidService,
    HeptagonalAntiprismSolidCalculator,
)
from .archimedean_solids import (
    ArchimedeanSolidServiceBase,
    ArchimedeanSolidCalculatorBase,
    CuboctahedronSolidService,
    CuboctahedronSolidCalculator,
    TruncatedTetrahedronSolidService,
    TruncatedTetrahedronSolidCalculator,
    TruncatedCubeSolidService,
    TruncatedCubeSolidCalculator,
    TruncatedOctahedronSolidService,
    TruncatedOctahedronSolidCalculator,
    RhombicuboctahedronSolidService,
    RhombicuboctahedronSolidCalculator,
    RhombicosidodecahedronSolidService,
    RhombicosidodecahedronSolidCalculator,
    TruncatedCuboctahedronSolidService,
    TruncatedCuboctahedronSolidCalculator,
    IcosidodecahedronSolidService,
    IcosidodecahedronSolidCalculator,
    TruncatedDodecahedronSolidService,
    TruncatedDodecahedronSolidCalculator,
    TruncatedIcosahedronSolidService,
    TruncatedIcosahedronSolidCalculator,
    TruncatedIcosidodecahedronSolidService,
    TruncatedIcosidodecahedronSolidCalculator,
    SnubCubeSolidService,
    SnubCubeSolidCalculator,
    SnubDodecahedronSolidService,
    SnubDodecahedronSolidCalculator,
)
from .torus_solid import TorusSolidService, TorusSolidCalculator
from .torus_knot_solid import TorusKnotSolidService, TorusKnotSolidCalculator

__all__ = [
    'GeometricShape',
    'ShapeProperty',
    'AnnulusShape',
    'CircleShape',
    'CrescentShape',
    'EllipseShape',
    'SquareShape',
    'RectangleShape',
    'ParallelogramShape',
    'RhombusShape',
    'TrapezoidShape',
    'IsoscelesTrapezoidShape',
    'KiteShape',
    'DeltoidShape',
    'EquilateralTriangleShape',
    'RightTriangleShape',
    'IsoscelesTriangleShape',
    'ScaleneTriangleShape',
    'AcuteTriangleShape',
    'ObtuseTriangleShape',
    'HeronianTriangleShape',
    'IsoscelesRightTriangleShape',
    'ThirtySixtyNinetyTriangleShape',
    'GoldenTriangleShape',
    'TriangleSolverShape',
    'CyclicQuadrilateralShape',
    'TangentialQuadrilateralShape',
    'BicentricQuadrilateralShape',
    'QuadrilateralSolverShape',
    'RegularPolygonShape',
    'Point',
    'polygonal_number_value',
    'centered_polygonal_value',
    'polygonal_number_points',
    'polygonal_outline_points',
    "star_number_value",
    "generalized_star_number_value",
    "generalized_star_number_points",
    "star_number_points",
    "max_radius",
    'RoseCurveShape',
    'VaultOfHestiaShape',
    'VesicaPiscisShape',
    'TetrahedronSolidService',
    'TetrahedronSolidCalculator',
    'CubeSolidService',
    'CubeSolidCalculator',
    'OctahedronSolidService',
    'OctahedronSolidCalculator',
    'DodecahedronSolidService',
    'DodecahedronSolidCalculator',
    'IcosahedronSolidService',
    'IcosahedronSolidCalculator',
    'TesseractSolidService',
    'TesseractSolidCalculator',
    'SquarePyramidSolidService',
    'SquarePyramidSolidCalculator',
    'SquarePyramidFrustumSolidService',
    'SquarePyramidFrustumSolidCalculator',
    'PentagonalPyramidFrustumSolidService',
    'PentagonalPyramidFrustumSolidCalculator',
    'HexagonalPyramidFrustumSolidService',
    'HexagonalPyramidFrustumSolidCalculator',
    'RectangularPyramidSolidService',
    'RectangularPyramidSolidCalculator',
    'RectangularPrismSolidService',
    'RectangularPrismSolidCalculator',
    'TriangularPyramidSolidService',
    'TriangularPyramidSolidCalculator',
    'PentagonalPyramidSolidService',
    'PentagonalPyramidSolidCalculator',
    'HexagonalPyramidSolidService',
    'HexagonalPyramidSolidCalculator',
    'HeptagonalPyramidSolidService',
    'HeptagonalPyramidSolidCalculator',
    'GoldenPyramidSolidService',
    'GoldenPyramidSolidCalculator',
    'StepPyramidSolidService',
    'StepPyramidSolidCalculator',
    'RegularPrismSolidServiceBase',
    'RegularPrismSolidCalculatorBase',
    'TriangularPrismSolidService',
    'TriangularPrismSolidCalculator',
    'PentagonalPrismSolidService',
    'PentagonalPrismSolidCalculator',
    'HexagonalPrismSolidService',
    'HexagonalPrismSolidCalculator',
    'OctagonalPrismSolidService',
    'OctagonalPrismSolidCalculator',
    'HeptagonalPrismSolidService',
    'HeptagonalPrismSolidCalculator',
    'ObliquePrismSolidService',
    'ObliquePrismSolidCalculator',
    'PrismaticFrustumSolidService',
    'PrismaticFrustumSolidCalculator',
    'RegularAntiprismSolidServiceBase',
    'RegularAntiprismSolidCalculatorBase',
    'TriangularAntiprismSolidService',
    'TriangularAntiprismSolidCalculator',
    'SquareAntiprismSolidService',
    'SquareAntiprismSolidCalculator',
    'PentagonalAntiprismSolidService',
    'PentagonalAntiprismSolidCalculator',
    'HexagonalAntiprismSolidService',
    'HexagonalAntiprismSolidCalculator',
    'OctagonalAntiprismSolidService',
    'OctagonalAntiprismSolidCalculator',
    'HeptagonalAntiprismSolidService',
    'HeptagonalAntiprismSolidCalculator',
    'ArchimedeanSolidServiceBase',
    'ArchimedeanSolidCalculatorBase',
    'CuboctahedronSolidService',
    'CuboctahedronSolidCalculator',
    'TruncatedTetrahedronSolidService',
    'TruncatedTetrahedronSolidCalculator',
    'TruncatedCubeSolidService',
    'TruncatedCubeSolidCalculator',
    'TruncatedOctahedronSolidService',
    'TruncatedOctahedronSolidCalculator',
    'RhombicuboctahedronSolidService',
    'RhombicuboctahedronSolidCalculator',
    'RhombicosidodecahedronSolidService',
    'RhombicosidodecahedronSolidCalculator',
    'TruncatedCuboctahedronSolidService',
    'TruncatedCuboctahedronSolidCalculator',
    'IcosidodecahedronSolidService',
    'IcosidodecahedronSolidCalculator',
    'TruncatedDodecahedronSolidService',
    'TruncatedDodecahedronSolidCalculator',
    'TruncatedIcosahedronSolidService',
    'TruncatedIcosahedronSolidCalculator',
    'TruncatedIcosidodecahedronSolidService',
    'TruncatedIcosidodecahedronSolidCalculator',
    'SnubCubeSolidService',
    'SnubCubeSolidCalculator',
    'SnubDodecahedronSolidService',
    'SnubDodecahedronSolidCalculator',
    'TorusSolidService',
    'TorusSolidCalculator',
    'TorusKnotSolidService',
    'TorusKnotSolidCalculator',
]

