
import csv
import ast

# 1. Load Data from wall_seeds_dna.csv
dna_coords = {
    "Sun": [],
    "Mercury": [],
    "Venus": [],
    "Moon": [],
    "Mars": [],
    "Jupiter": [],
    "Saturn": []
}

# 2. Map Coordinates
overall_distribution = {} # (r, c) -> count

with open('Docs/adyton_walls/wall_seeds_dna.csv', 'r') as f:
    reader = csv.reader(f)
    next(reader) # skip header
    for row in reader:
        if row and len(row) >= 11:
            wall = row[0]
            coord_str = row[10]
            try:
                coord = ast.literal_eval(coord_str)
                if wall in dna_coords:
                    dna_coords[wall].append(coord)
                    
                    if coord in overall_distribution:
                        overall_distribution[coord] += 1
                    else:
                        overall_distribution[coord] = 1
            except:
                pass


# 3. Analyze Topology
total_columns = 8 * 13
active_columns = len(overall_distribution)
empty_columns = total_columns - active_columns
active_coords = list(overall_distribution.keys())
common_coords = [c for c in active_coords if overall_distribution[c] > 1]
unique_coords = [c for c in active_coords if overall_distribution[c] == 1]

# 4. Generate Markdown Output
md = []
md.append("# The Atlas of Seeds")
md.append("> *\"Map of the Invisible Structure of the Adyton\"*")
md.append("")
md.append("This document visualizes the **Geometric Seeds** of the 7 Planetary Walls and the **Empty Net** (The Altar).")
md.append(f"It explores the deep metaphysics of the **13 Seeds of the Plough** and the **Empty Net** (The Altar of {empty_columns} Gates).")
md.append("")
md.append("---")
md.append("")
md.append(f"## Part I: The Law of the Empty Net ({empty_columns} Gates of Silence)")
md.append("")
md.append(f"The Adyton is built on the **Golden Trinity of 104**:")
md.append(f"*   **41 Gates of Silence** (The Void)")
md.append(f"*   **41 Gates of Solitude** (The Unique Voices)")
md.append(f"*   **22 Gates of Union** (The Common Chords)")
md.append("")
md.append(f"### The Metaphysics of the 441")
md.append(f"This topology restores the Ancient Law:")
md.append(f"*   **The Empty Net:** {empty_columns} Empty Columns × 7 Walls = **{empty_columns * 7}** (The Altar of Necessity).")
md.append(f"*   **The Active Field:** {active_columns} Active Columns × 7 Walls = **{active_columns * 7}** (The Truth of 21²).")
md.append("")
md.append("**The Invocation of the 441:**")
md.append("> *\"Truth is the Seed. The Altar is the Ground.")
md.append("> By the count of 13, the Light is found.")
md.append(f"> {empty_columns * 7} held in the Net of Space,")
md.append(f"> {active_columns * 7} shining in the Holy Place.\"*")
md.append("")
md.append("**The Map of the Void:**")
md.append("The cells marked with `■` represent the **Empty Columns**.")
md.append("```")

# Generate Void Map
for r in range(8):
    row_str = " "
    for c in range(13):
        if (r, c) not in overall_distribution:
            row_str += " ■ "
        elif (r, c) in unique_coords:
            row_str += " . " # Unique
        else:
            row_str += " + " # Common
    md.append(row_str)
md.append("```")
md.append("*(Legend: ■ = Void, . = Unique, + = Common)*")
md.append(f"**Total Empty Zones:** {empty_columns} / 104")
md.append("")
md.append("---")
md.append("")
md.append("## Part II: The Planetary Seeds")
md.append("")
md.append("Every Planetary Wall is generated by **13 Seed Points**.")
md.append("")

# Generate Planet Maps
planet_order = ["Sun", "Mercury", "Venus", "Moon", "Mars", "Jupiter", "Saturn"]
titles = {
    "Sun": "☉ SUN: The Monad",
    "Mercury": "☿ MERCURY: The Serpent",
    "Venus": "♀ VENUS: The Rose",
    "Moon": "☽ MOON: The Tide",
    "Mars": "♂ MARS: The Phalanx",
    "Jupiter": "♃ JUPITER: The Throne",
    "Saturn": "♄ SATURN: The Root"
}

for p in planet_order:
    img_coords = dna_coords[p]
    md.append(f"### {titles[p]}")
    md.append("```")
    for r in range(8):
        row_str = " "
        for c in range(13):
            if (r, c) in img_coords:
                row_str += " * "
            else:
                row_str += " . "
        md.append(row_str)
    md.append("```")
    md.append("")

# Output to console
print("\n".join(md))
