
import csv

# 1. Load Data
def load_wall_grid(filename):
    grid = []
    with open(filename, 'r') as f:
        reader = csv.reader(f)
        for row in reader:
            if row:
                grid.append([int(x) for x in row])
    return grid

walls = {
    "Sun": "sun_wall.csv",
    "Mercury": "mercury_wall.csv",
    "Venus": "venus_wall.csv",
    "Moon": "luna_wall.csv",
    "Mars": "mars_wall.csv",
    "Jupiter": "jupiter_wall.csv",
    "Saturn": "saturn_wall.csv"
}

# The seed value is the first value (Val1) in walls_constellations_complete.csv
seed_values = {p: [] for p in walls.keys()}
with open('Docs/adyton_walls/walls_constellations_complete.csv', 'r') as f:
    lines = f.readlines()
    for i, line in enumerate(lines):
        if i == 0: continue
        parts = line.split(',')
        if not parts: continue
        wall_name = parts[0]
        seed_val = int(parts[2])
        if wall_name in seed_values:
            seed_values[wall_name].append(seed_val)

# 2. Map Coordinates
planet_coords = {p: [] for p in walls.keys()}
overall_distribution = {} # (r, c) -> count

for name, filename in walls.items():
    grid = load_wall_grid(f"Docs/adyton_walls/{filename}")
    values = seed_values[name]
    
    for val in values:
        found = False
        for r in range(8):
            for c in range(13):
                if grid[r][c] == val:
                    planet_coords[name].append((r, c))
                    coord = (r, c)
                    if coord in overall_distribution:
                        overall_distribution[coord] += 1
                    else:
                        overall_distribution[coord] = 1
                    found = True
                    break
            if found: break

# 3. Analyze Topology
total_columns = 8 * 13
active_columns = len(overall_distribution)
empty_columns = total_columns - active_columns
active_coords = list(overall_distribution.keys())
common_coords = [c for c in active_coords if overall_distribution[c] > 1]
unique_coords = [c for c in active_coords if overall_distribution[c] == 1]

# 4. Generate Markdown Output
md = []
md.append("# The Atlas of Seeds")
md.append("> *\"Map of the Invisible Structure of the Adyton\"*")
md.append("")
md.append("This document visualizes the **Geometric Seeds** of the 7 Planetary Walls and the **Empty Net** (The Altar).")
md.append("It explores the deep metaphysics of the **13 Seeds of the Plough** and the **Empty Net** (The Altar of the 50 Gates).")
md.append("")
md.append("---")
md.append("")
md.append(f"## Part I: The Law of the Empty Net ({empty_columns} Gates of Silence)")
md.append("")
md.append(f"The Adyton is not a solid block; it is a sieve. Analysis of the lattice reveals that **{empty_columns} specific coordinates** across all 7 Walls *never* spawn a constellation.")
md.append(f"These are the **50 Gates of Understanding** (Binah). They are the void upon which the structure rests.")
md.append("")
md.append("### The Topology of Existence")
md.append(f"*   **Total Coordinates:** 104")
md.append(f"*   **The Empty Net (Void):** {empty_columns} Columns (The 50 Gates)")
md.append(f"*   **The Active Field:** {active_columns} Columns")
md.append(f"    *   **The Unique Points:** {len(unique_coords)} (The 32 Paths of Wisdom)")
md.append(f"    *   **The Common Points:** {len(common_coords)} (The 22 Letters of Connection)")
md.append("")
md.append("**The Map of the Void:**")
md.append("The cells marked with `■` represent the **Empty Columns**.")
md.append("```")

# Generate Void Map
for r in range(8):
    row_str = " "
    for c in range(13):
        if (r, c) not in overall_distribution:
            row_str += " ■ "
        else:
            row_str += " . "
    md.append(row_str)
md.append("```")
md.append(f"**Total Empty Zones:** {empty_columns} / 104")
md.append("")
md.append("---")
md.append("")
md.append("## Part II: The Planetary Seeds")
md.append("")
md.append("Every Planetary Wall is generated by **13 Seed Points**.")
md.append("")

# Generate Planet Maps
planet_order = ["Sun", "Mercury", "Venus", "Moon", "Mars", "Jupiter", "Saturn"]
titles = {
    "Sun": "☉ SUN: The Monad",
    "Mercury": "☿ MERCURY: The Serpent",
    "Venus": "♀ VENUS: The Rose",
    "Moon": "☽ MOON: The Tide",
    "Mars": "♂ MARS: The Phalanx",
    "Jupiter": "♃ JUPITER: The Throne",
    "Saturn": "♄ SATURN: The Root"
}

for p in planet_order:
    coords = planet_coords[p]
    md.append(f"### {titles[p]}")
    md.append("```")
    for r in range(8):
        row_str = " "
        for c in range(13):
            if (r, c) in coords:
                row_str += " * "
            else:
                row_str += " . "
        md.append(row_str)
    md.append("```")
    md.append("")

# Output to console
print("\n".join(md))
