from typing import Callable, List, Optional, Dict, Any

from ..services.vault_of_hestia_shape import VaultOfHestiaShape
from ..services.seed_of_life_shape import SeedOfLifeShape
from ..services import (
    AnnulusShape,
    CircleShape,
    CrescentShape,
    EllipseShape,
    RoseCurveShape,
    SquareShape,
    RectangleShape,
    ParallelogramShape,
    RhombusShape,
    TrapezoidShape,
    IsoscelesTrapezoidShape,
    KiteShape,
    DeltoidShape,
    EquilateralTriangleShape,
    RightTriangleShape,
    IsoscelesTriangleShape,
    ScaleneTriangleShape,
    AcuteTriangleShape,
    ObtuseTriangleShape,
    HeronianTriangleShape,
    IsoscelesRightTriangleShape,
    ThirtySixtyNinetyTriangleShape,
    GoldenTriangleShape,
    TriangleSolverShape,
    VaultOfHestiaShape,
    CyclicQuadrilateralShape,
    TangentialQuadrilateralShape,
    BicentricQuadrilateralShape,
    QuadrilateralSolverShape,
    RegularPolygonShape,
    VesicaPiscisShape,
    TetrahedronSolidService,
    TetrahedronSolidCalculator,
    CubeSolidService,
    CubeSolidCalculator,
    OctahedronSolidService,
    OctahedronSolidCalculator,
    DodecahedronSolidService,
    DodecahedronSolidCalculator,
    IcosahedronSolidService,
    IcosahedronSolidCalculator,
    TesseractSolidService,
    TesseractSolidCalculator,
    SquarePyramidSolidService,
    SquarePyramidSolidCalculator,
    SquarePyramidFrustumSolidService,
    SquarePyramidFrustumSolidCalculator,
    PentagonalPyramidFrustumSolidService,
    PentagonalPyramidFrustumSolidCalculator,
    HexagonalPyramidFrustumSolidService,
    HexagonalPyramidFrustumSolidCalculator,
    RectangularPyramidSolidService,
    RectangularPyramidSolidCalculator,
    TriangularPyramidSolidService,
    TriangularPyramidSolidCalculator,
    PentagonalPyramidSolidService,
    PentagonalPyramidSolidCalculator,
    HexagonalPyramidSolidService,
    HexagonalPyramidSolidCalculator,
    HeptagonalPyramidSolidService,
    HeptagonalPyramidSolidCalculator,
    GoldenPyramidSolidService,
    GoldenPyramidSolidCalculator,
    StepPyramidSolidService,
    StepPyramidSolidCalculator,
    RectangularPrismSolidService,
    RectangularPrismSolidCalculator,
    TriangularPrismSolidService,
    TriangularPrismSolidCalculator,
    PentagonalPrismSolidService,
    PentagonalPrismSolidCalculator,
    HexagonalPrismSolidService,
    HexagonalPrismSolidCalculator,
    OctagonalPrismSolidService,
    OctagonalPrismSolidCalculator,
    HeptagonalPrismSolidService,
    HeptagonalPrismSolidCalculator,
    ObliquePrismSolidService,
    ObliquePrismSolidCalculator,
    TorusSolidService,
    TorusSolidCalculator,
    TorusKnotSolidService,
    TorusKnotSolidCalculator,
    PrismaticFrustumSolidService,
    PrismaticFrustumSolidCalculator,
    TriangularAntiprismSolidService,
    TriangularAntiprismSolidCalculator,
    SquareAntiprismSolidService,
    SquareAntiprismSolidCalculator,
    PentagonalAntiprismSolidService,
    PentagonalAntiprismSolidCalculator,
    HexagonalAntiprismSolidService,
    HexagonalAntiprismSolidCalculator,
    OctagonalAntiprismSolidService,
    OctagonalAntiprismSolidCalculator,
    HeptagonalAntiprismSolidService,
    HeptagonalAntiprismSolidCalculator,
    CuboctahedronSolidService,
    CuboctahedronSolidCalculator,
    TruncatedTetrahedronSolidService,
    TruncatedTetrahedronSolidCalculator,
    TruncatedCubeSolidService,
    TruncatedCubeSolidCalculator,
    TruncatedOctahedronSolidService,
    TruncatedOctahedronSolidCalculator,
    RhombicuboctahedronSolidService,
    RhombicuboctahedronSolidCalculator,
    RhombicosidodecahedronSolidService,
    RhombicosidodecahedronSolidCalculator,
    TruncatedCuboctahedronSolidService,
    TruncatedCuboctahedronSolidCalculator,
    IcosidodecahedronSolidService,
    IcosidodecahedronSolidCalculator,
    TruncatedDodecahedronSolidService,
    TruncatedDodecahedronSolidCalculator,
    TruncatedIcosahedronSolidService,
    TruncatedIcosahedronSolidCalculator,
    TruncatedIcosidodecahedronSolidService,
    TruncatedIcosidodecahedronSolidCalculator,
    SnubCubeSolidService,
    SnubCubeSolidCalculator,
    SnubDodecahedronSolidService,
    SnubDodecahedronSolidCalculator,
    SnubCubeSolidService,
    SnubCubeSolidCalculator,
    SnubDodecahedronSolidService,
    SnubDodecahedronSolidCalculator,
    VaultOfHestiaSolidService,
    VaultOfHestiaSolidCalculator,
    SphereSolidService,
    SphereSolidCalculator,
    CylinderSolidService,
    CylinderSolidCalculator,
    ConeSolidService,
    ConeSolidCalculator,
    GeneralPrismSolidService,
    GeneralPrismSolidCalculator,
    GeneralAntiprismSolidService,
    GeneralAntiprismSolidCalculator,
    SnubAntiprismSolidService,
    SnubAntiprismSolidCalculator,
    GyroelongatedSquarePrismSolidService,
    GyroelongatedSquarePrismSolidCalculator,
    GeneralPyramidSolidService,
    GeneralPyramidSolidCalculator,
)

from .esoteric_definitions import ESOTERIC_DEFINITIONS

def _category(name: str, icon: str, tagline: str, shapes: List[dict], menu: Optional[List[Any]] = None) -> dict:
    return {
        'name': name,
        'icon': icon,
        'tagline': tagline,
        'shapes': shapes,
        'menu': menu,
    }

CATEGORY_DEFINITIONS: List[dict] = [
    _category(
        name="Circles",
        icon="◯",
        tagline="Curves, arcs, and ellipses",
        shapes=[
            {
                'name': 'Circle',
                'summary': 'Radius, diameter, circumference, area',
                'factory': CircleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Circle'],
            },
            {
                'name': 'Oval (Ellipse)',
                'summary': 'Semi-major/minor axes, eccentricity, Ramanujan perimeter',
                'factory': EllipseShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Oval (Ellipse)'],
            },
            {
                'name': 'Annulus',
                'summary': 'Ring width, concentric circumferences, area delta',
                'factory': AnnulusShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Annulus'],
            },
            {
                'name': 'Crescent',
                'summary': 'Lune carved by offset inner circle with overlap metrics',
                'factory': CrescentShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Crescent'],
            },
            {
                'name': 'Vesica Piscis',
                'summary': 'Sacred lens of two equal circles with arc + area data',
                'factory': VesicaPiscisShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Vesica Piscis'],
            },
            {
                'name': 'Rose (Rhodonea Curve)',
                'summary': 'Amplitude and harmonic-driven petal curves',
                'factory': RoseCurveShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Rose (Rhodonea Curve)'],
            },
        ],
    ),
    _category(
        name="Triangles",
        icon="△",
        tagline="Classical sacred triples",
        shapes=[
            {
                'name': 'Equilateral Triangle',
                'summary': 'Side, height, area, radii',
                'factory': EquilateralTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Equilateral Triangle'],
            },
            {
                'name': 'Right Triangle',
                'summary': 'Base, height, hypotenuse, area',
                'factory': RightTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Right Triangle'],
            },
            {
                'name': 'Isosceles Triangle',
                'summary': 'Equal legs from base + height inputs with area/perimeter',
                'factory': IsoscelesTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Isosceles Triangle'],
            },
            {
                'name': 'Scalene Triangle',
                'summary': 'Three unequal sides with SSS validation, altitudes, radii',
                'factory': ScaleneTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Scalene Triangle'],
            },
            {
                'name': 'Acute Triangle',
                'summary': 'All interior angles < 90° with altitude breakdowns',
                'factory': AcuteTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Acute Triangle'],
            },
            {
                'name': 'Obtuse Triangle',
                'summary': 'Detects >90° angle scenarios with exterior altitude tracing',
                'factory': ObtuseTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Obtuse Triangle'],
            },
            {
                'name': 'Isosceles Right Triangle (45-45-90)',
                'summary': '45-45-90 triangle with √2 leg relationships & radii',
                'factory': IsoscelesRightTriangleShape,
            },
            {
                'name': '30-60-90 Triangle',
                'summary': 'Half-equilateral proportions with √3 ratios and heights',
                'factory': ThirtySixtyNinetyTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['30-60-90 Triangle'],
            },
            {
                'name': 'Golden Triangle',
                'summary': 'Isosceles phi-based triangle with derived short side + area',
                'factory': GoldenTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Golden Triangle'],
            },
            {
                'name': 'Heronian Triangle',
                'summary': 'Integer side + area validation using Heron’s formula',
                'factory': HeronianTriangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Heronian Triangle'],
            },
            {
                'name': 'Triangle Solver (any sides/angles)',
                'summary': 'General SAS/ASA/SSA/SSS solver with visualization',
                'factory': TriangleSolverShape,
            },
        ],
    ),
    _category(
        name="Sacred Geometry",
        icon="☥",
        tagline="Esoteric and mystical constructions",
        shapes=[
            {
                'name': 'Vault of Hestia',
                'summary': 'Square-Triangle-Circle generator of Phi',
                'factory': VaultOfHestiaShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Vault of Hestia'],
            },
            {
                'name': 'Seed of Life',
                'summary': 'Seven circles in hexagonal symmetry representing creation',
                'factory': SeedOfLifeShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Seed of Life'],
            },
            {
                'name': 'Vault of Hestia (3D)',
                'summary': 'Cube holding a Pyramid holding a Sphere (Phi Generator)',
                'type': 'solid_viewer',
                'solid_id': 'vault_of_hestia_3d',
                'esoteric_description': ESOTERIC_DEFINITIONS['Vault of Hestia'],
            },
        ],
    ),
    _category(
        name="Quadrilaterals",
        icon="▭",
        tagline="Squares, rectangles, and beyond",
        shapes=[
            {
                'name': 'Square',
                'summary': 'Side, perimeter, area, diagonal',
                'factory': SquareShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Square'],
            },
            {
                'name': 'Rectangle',
                'summary': 'Length, width, perimeter, diagonal',
                'factory': RectangleShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Rectangle'],
            },
            {
                'name': 'Parallelogram',
                'summary': 'Opposite sides parallel with angle, height, and diagonal data',
                'factory': ParallelogramShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Parallelogram'],
            },
            {
                'name': 'Rhombus',
                'summary': 'Equal sides with diagonal, area, and height solvers',
                'factory': RhombusShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Rhombus'],
            },
            {
                'name': 'Trapezoid',
                'summary': 'General trapezoid with base, leg, and altitude validation',
                'factory': TrapezoidShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Trapezoid'],
            },
            {
                'name': 'Isosceles Trapezoid',
                'summary': 'Symmetric trapezoid with equal legs and diagonal readouts',
                'factory': IsoscelesTrapezoidShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Isosceles Trapezoid'],
            },
            {
                'name': 'Kite',
                'summary': 'Adjacent equal sides with diagonal + area from side-angle inputs',
                'factory': KiteShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Kite'],
            },
            {
                'name': 'Deltoid / Dart',
                'summary': 'Concave kite (dart) variant using reflex angles',
                'factory': DeltoidShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Deltoid / Dart'],
            },
            {
                'name': 'Cyclic Quadrilateral',
                'summary': 'All vertices on a circle with Brahmagupta area and R',
                'factory': CyclicQuadrilateralShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Cyclic Quadrilateral'],
            },
            {
                'name': 'Tangential Quadrilateral',
                'summary': 'Incircle touches every side with Pitot + inradius checks',
                'factory': TangentialQuadrilateralShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Tangential Quadrilateral'],
            },
            {
                'name': 'Bicentric Quadrilateral',
                'summary': 'Simultaneously cyclic and tangential (incircle + circumcircle)',
                'factory': BicentricQuadrilateralShape,
                'esoteric_description': ESOTERIC_DEFINITIONS['Bicentric Quadrilateral'],
            },
            {
                'name': 'General Quadrilateral Solver',
                'summary': 'Mix sides with diagonal lengths + included diagonal angle',
                'factory': QuadrilateralSolverShape,
            },
        ],
    ),
    _category(
        name="Polygons",
        icon="⬢",
        tagline="Regular and star polygons",
        shapes=[
            {
                'name': 'Regular Pentagon (5-gon)',
                'summary': 'Equal sides and angles – sacred pentagonal ratios',
                'polygon_sides': 5,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Pentagon (5-gon)'],
            },
            {
                'name': 'Regular Hexagon (6-gon)',
                'summary': 'Hexagonal lattices, honeycomb symmetries',
                'polygon_sides': 6,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Hexagon (6-gon)'],
            },
            {
                'name': 'Regular Heptagon (7-gon)',
                'summary': 'Septenary geometry studies',
                'polygon_sides': 7,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Heptagon (7-gon)'],
            },
            {
                'name': 'Regular Octagon (8-gon)',
                'summary': 'Stop-sign symmetry, eastern mandalas',
                'polygon_sides': 8,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Octagon (8-gon)'],
            },
            {
                'name': 'Regular Nonagon (9-gon)',
                'summary': 'Ninefold geometry explorations',
                'polygon_sides': 9,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Nonagon (9-gon)'],
            },
            {
                'name': 'Regular Decagon (10-gon)',
                'summary': 'Golden ratio relationships in tenfold form',
                'polygon_sides': 10,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Decagon (10-gon)'],
            },
            {
                'name': 'Regular Hendecagon (11-gon)',
                'summary': 'Rarer elevenfold rotational symmetry',
                'polygon_sides': 11,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Hendecagon (11-gon)'],
            },
            {
                'name': 'Regular Dodecagon (12-gon)',
                'summary': 'Twelvefold cycles and sacred geometry',
                'polygon_sides': 12,
                'esoteric_description': ESOTERIC_DEFINITIONS['Regular Dodecagon (12-gon)'],
            },
            {
                'name': 'Any Regular n-gon',
                'summary': 'Choose any number of sides ≥ 3',
                'type': 'regular_polygon_custom',
            },
        ],
    ),
    _category(
        name="Pyramids",
        icon="⌂",
        tagline="Tapered solids rising from sacred bases",
        shapes=[
            {
                'name': 'Square Pyramid',
                'summary': 'Base edge, slant height, apothem, volume',
                'type': 'solid_viewer',
                'solid_id': 'square_pyramid',
                'esoteric_description': ESOTERIC_DEFINITIONS['Square Pyramid'],
            },
            {
                'name': 'Rectangular Pyramid',
                'summary': 'Independent base edges with dual slant heights and volume',
                'type': 'solid_viewer',
                'solid_id': 'rectangular_pyramid',
                'esoteric_description': ESOTERIC_DEFINITIONS['Rectangular Pyramid'],
            },
            {
                'name': 'Equilateral Triangular Pyramid (Tetrahedral)',
                'summary': 'Equilateral base with adjustable apex height, slant, and volume',
                'type': 'solid_viewer',
                'solid_id': 'triangular_pyramid',
                'esoteric_description': ESOTERIC_DEFINITIONS['Equilateral Triangular Pyramid'],
            },
            {
                'name': 'Regular Pentagonal Pyramid',
                'summary': 'Fivefold symmetry with apothem, slant, and lateral metrics',
                'type': 'solid_viewer',
                'solid_id': 'pentagonal_pyramid',
                'esoteric_description': ESOTERIC_DEFINITIONS['Pentagonal Pyramid'],
            },
            {
                'name': 'Regular Hexagonal Pyramid',
                'summary': 'Honeycomb-style base with live perimeter and volume solving',
                'type': 'solid_viewer',
                'solid_id': 'hexagonal_pyramid',
                'esoteric_description': ESOTERIC_DEFINITIONS['Hexagonal Pyramid'],
            },
            {
                'name': 'Regular Heptagonal Pyramid',
                'summary': 'Sevenfold base showcasing rare apothem and slant couplings',
                'type': 'solid_viewer',
                'solid_id': 'heptagonal_pyramid',
                'esoteric_description': ESOTERIC_DEFINITIONS['Heptagonal Pyramid'],
            },
            {
                'name': 'Oblique Pyramid',
                'summary': 'Coming soon: apex offset with lateral face resolution',
                'status': 'Coming Soon',
                'factory': None,
            },
            {
                'name': 'Square Pyramid Frustum',
                'summary': 'Dual-base truncated square pyramid with coupled slant metrics',
                'type': 'solid_viewer',
                'solid_id': 'square_pyramid_frustum',
                'esoteric_description': ESOTERIC_DEFINITIONS['Square Frustum'],
            },
            {
                'name': 'Pentagonal Pyramid Frustum',
                'summary': 'Fivefold truncated pyramid with dual perimeter + slant metrics',
                'type': 'solid_viewer',
                'solid_id': 'pentagonal_pyramid_frustum',
                'esoteric_description': ESOTERIC_DEFINITIONS['Pentagonal Frustum'],
            },
            {
                'name': 'Hexagonal Pyramid Frustum',
                'summary': 'Honeycomb-based truncated pyramid with apothem-driven slant control',
                'type': 'solid_viewer',
                'solid_id': 'hexagonal_pyramid_frustum',
                'esoteric_description': ESOTERIC_DEFINITIONS['Hexagonal Frustum'],
            },
            {
                'name': 'Golden Pyramid',
                'summary': 'Great Pyramid inspired φ-ratio pyramid with derived slant + height',
                'type': 'solid_viewer',
                'solid_id': 'golden_pyramid',
                'esoteric_description': ESOTERIC_DEFINITIONS['Golden Pyramid'],
            },
            {
                'name': 'Step Pyramid',
                'summary': 'Tiered mastaba stack with adjustable steps and cumulative metrics',
                'type': 'solid_viewer',
                'solid_id': 'step_pyramid',
            },
            {
                'name': 'General n-gonal Pyramid Solver',
                'summary': 'Configurable pyramid supporting any base polygon (n ≥ 3) with dynamic apex.',
                'type': 'solid_viewer',
                'solid_id': 'general_pyramid',
            },
        ],
        menu=[
            {
                'label': 'Right Regular Pyramids',
                'items': [
                    'Square Pyramid',
                    'Rectangular Pyramid',
                    'Equilateral Triangular Pyramid (Tetrahedral)',
                    'Regular Pentagonal Pyramid',
                    'Regular Hexagonal Pyramid',
                    'Regular Heptagonal Pyramid',
                ],
            },
            {
                'label': 'Oblique & Frustums',
                'items': [
                    'Oblique Pyramid',
                    'Square Pyramid Frustum',
                    'Pentagonal Pyramid Frustum',
                    'Hexagonal Pyramid Frustum',
                ],
            },
            {
                'label': 'Sacred & General Tools',
                'items': [
                    'Golden Pyramid',
                    'Step Pyramid',
                    'General n-gonal Pyramid Solver',
                ],
            },
        ],
    ),
    _category(
        name="Prisms",
        icon="▱",
        tagline="Uniform cross-section solids",
        shapes=[
            {
                'name': 'Triangular Prism',
                'summary': 'Equilateral base prism with apothem, lateral area, and volume solving.',
                'type': 'solid_viewer',
                'solid_id': 'triangular_prism',
            },
            {
                'name': 'Rectangular Prism',
                'summary': 'Independent length × width × height box with diagonal readouts.',
                'type': 'solid_viewer',
                'solid_id': 'rectangular_prism',
            },
            {
                'name': 'Pentagonal Prism',
                'summary': 'Fivefold regular prism showing perimeter, apothem, and volume coupling.',
                'type': 'solid_viewer',
                'solid_id': 'pentagonal_prism',
            },
            {
                'name': 'Hexagonal Prism',
                'summary': 'Honeycomb regular prism with live lateral/surface area metrics.',
                'type': 'solid_viewer',
                'solid_id': 'hexagonal_prism',
            },
            {
                'name': 'Heptagonal Prism',
                'summary': 'Sevenfold base prism showcasing rare perimeter/apothem couplings.',
                'type': 'solid_viewer',
                'solid_id': 'heptagonal_prism',
            },
            {
                'name': 'Octagonal Prism',
                'summary': 'Stop-sign base prism featuring radius, apothem, and face analytics.',
                'type': 'solid_viewer',
                'solid_id': 'octagonal_prism',
            },
            {
                'name': 'Oblique Prism',
                'summary': 'Skewed regular prism with editable lateral offset.',
                'type': 'solid_viewer',
                'solid_id': 'oblique_prism',
            },
            {
                'name': 'Prismatic Frustum',
                'summary': 'Regular prism truncated between dual polygon bases.',
                'type': 'solid_viewer',
                'solid_id': 'prismatic_frustum',
                'esoteric_description': ESOTERIC_DEFINITIONS['Prismatic Frustum'],
            },
            {
                'name': 'Gyroelongated Square Prism',
                'summary': 'Hybrid Johnson solid combining square prism and square antiprism logic.',
                'type': 'solid_viewer',
                'solid_id': 'gyro_square_prism',
                'esoteric_description': ESOTERIC_DEFINITIONS['Gyroelongated Square Prism'],
            },
            {
                'name': 'General n-gonal Prism Solver',
                'summary': 'Configurable prism supporting any base polygon (n ≥ 3) with dynamic extrusion.',
                'type': 'solid_viewer',
                'solid_id': 'general_prism',
            },
            {
                'name': 'Prism Net Explorer',
                'summary': 'Coming soon: unfoldable nets and face adjacency maps',
                'status': 'Coming Soon',
                'factory': None,
            },
        ],
        menu=[
            {
                'label': 'Right Prisms',
                'items': [
                    'Triangular Prism',
                    'Rectangular Prism',
                    'Pentagonal Prism',
                    'Hexagonal Prism',
                    'Heptagonal Prism',
                    'Octagonal Prism',
                ],
            },
            {
                'label': 'Oblique & Truncated Forms',
                'items': [
                    'Oblique Prism',
                    'Prismatic Frustum',
                    'Gyroelongated Square Prism',
                ],
            },
            {
                'label': 'Explorers & Solvers',
                'items': [
                    'General n-gonal Prism Solver',
                    'Prism Net Explorer',
                ],
            },
        ],
    ),
    _category(
        name="Antiprisms",
        icon="⧖",
        tagline="Twisted twin-base solids",
        shapes=[
            {
                'name': 'Triangular Antiprism',
                'summary': 'Dual rotated triangles joined by equilateral lateral faces.',
                'type': 'solid_viewer',
                'solid_id': 'triangular_antiprism',
                'esoteric_description': ESOTERIC_DEFINITIONS['Triangular Antiprism'],
            },
            {
                'name': 'Square Antiprism',
                'summary': 'Square bases rotated 45° with eight congruent triangles.',
                'type': 'solid_viewer',
                'solid_id': 'square_antiprism',
                'esoteric_description': ESOTERIC_DEFINITIONS['Square Antiprism'],
            },
            {
                'name': 'Pentagonal Antiprism',
                'summary': 'Decagonal waist linking rotated pentagons with ten faces.',
                'type': 'solid_viewer',
                'solid_id': 'pentagonal_antiprism',
                'esoteric_description': ESOTERIC_DEFINITIONS['Pentagonal Antiprism'],
            },
            {
                'name': 'Hexagonal Antiprism',
                'summary': 'Staggered honeycomb pair producing twelve lateral triangles.',
                'type': 'solid_viewer',
                'solid_id': 'hexagonal_antiprism',
                'esoteric_description': ESOTERIC_DEFINITIONS['Hexagonal Antiprism'],
            },
            {
                'name': 'Heptagonal Antiprism',
                'summary': 'Sevenfold antiprism with fourteen lateral equilateral faces.',
                'type': 'solid_viewer',
                'solid_id': 'heptagonal_antiprism',
                'esoteric_description': ESOTERIC_DEFINITIONS['Heptagonal Antiprism'],
            },
            {
                'name': 'Octagonal Antiprism',
                'summary': 'Sixteen-triangle belt between rotated octagons.',
                'type': 'solid_viewer',
                'solid_id': 'octagonal_antiprism',
                'esoteric_description': ESOTERIC_DEFINITIONS['Octagonal Antiprism'],
            },
            {
                'name': 'Snub Antiprism',
                'summary': 'Snub square antiprism (J85) with 26 faces (24 triangles, 2 squares).',
                'type': 'solid_viewer',
                'solid_id': 'snub_square_antiprism',
            },
            {
                'name': 'Twisted Icosahedral Antiprism',
                'summary': 'High-order decagonal antiprism (n=10) approximating the icosahedron boundary.',
                'type': 'solid_viewer',
                'solid_id': 'twisted_icosahedral_antiprism',
            },
            {
                'name': 'General n-gonal Antiprism Solver',
                'summary': 'Configurable antiprism supporting any base polygon (n ≥ 3) with twist solving.',
                'type': 'solid_viewer',
                'solid_id': 'general_antiprism',
            },
            {
                'name': 'Antiprism Net Explorer',
                'summary': 'Coming soon: unfolding studies for twisted solids',
                'status': 'Coming Soon',
                'factory': None,
            },
        ],
        menu=[
            {
                'label': 'Standard Antiprisms',
                'items': [
                    'Triangular Antiprism',
                    'Square Antiprism',
                    'Pentagonal Antiprism',
                    'Hexagonal Antiprism',
                    'Heptagonal Antiprism',
                    'Octagonal Antiprism',
                ],
            },
            {
                'label': 'Advanced & Chiral',
                'items': [
                    'Snub Antiprism',
                    'Twisted Icosahedral Antiprism',
                ],
            },
            {
                'label': 'Tools & Explorers',
                'items': [
                    'General n-gonal Antiprism Solver',
                    'Antiprism Net Explorer',
                ],
            },
        ],
    ),
    _category(
        name="Platonic Solids",
        icon="◆",
        tagline="Perfect 3D symmetry",
        shapes=[
            {
                'name': 'Tetrahedron',
                'summary': 'Edge, height, area, volume',
                'type': 'solid_viewer',
                'solid_id': 'tetrahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Tetrahedron'],
            },
            {
                'name': 'Cube',
                'summary': 'Edge, diagonals, volume',
                'type': 'solid_viewer',
                'solid_id': 'cube',
                'esoteric_description': ESOTERIC_DEFINITIONS['Cube'],
            },
            {
                'name': 'Octahedron',
                'summary': 'Dual of cube with triangular faces',
                'type': 'solid_viewer',
                'solid_id': 'octahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Octahedron'],
            },
            {
                'name': 'Dodecahedron',
                'summary': 'Sacred pentagonal faces',
                'type': 'solid_viewer',
                'solid_id': 'dodecahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Dodecahedron'],
            },
            {
                'name': 'Icosahedron',
                'summary': 'Twenty equilateral faces and golden ratios',
                'type': 'solid_viewer',
                'solid_id': 'icosahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Icosahedron'],
            },
        ],
    ),
    _category(
        name="Archimedean Solids",
        icon="◇",
        tagline="Truncated and blended forms",
        shapes=[
            {
                'name': 'Truncated Tetrahedron',
                'summary': 'Regular tetra unfolded into 4 triangles + 4 hexagons.',
                'type': 'solid_viewer',
                'solid_id': 'truncated_tetrahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Truncated Tetrahedron'],
            },
            {
                'name': 'Cuboctahedron',
                'summary': 'Eight triangles and six squares sharing uniform edges.',
                'type': 'solid_viewer',
                'solid_id': 'cuboctahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Cuboctahedron'],
            },
            {
                'name': 'Truncated Cube',
                'summary': 'Octagon-square composition generated by trimming cube corners.',
                'type': 'solid_viewer',
                'solid_id': 'truncated_cube',
                'esoteric_description': ESOTERIC_DEFINITIONS['Truncated Cube'],
            },
            {
                'name': 'Truncated Octahedron',
                'summary': 'Space-filling solid blending hexagons with squares.',
                'type': 'solid_viewer',
                'solid_id': 'truncated_octahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Truncated Octahedron'],
            },
            {
                'name': 'Rhombicuboctahedron',
                'summary': 'Uniform mix of 18 squares and 8 triangles with full symmetry.',
                'type': 'solid_viewer',
                'solid_id': 'rhombicuboctahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Rhombicuboctahedron'],
            },
            {
                'name': 'Truncated Cuboctahedron',
                'summary': 'Great rhombicuboctahedron weaving hexagons, squares, and octagons.',
                'type': 'solid_viewer',
                'solid_id': 'truncated_cuboctahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Great Rhombicuboctahedron'],
            },
            {
                'name': 'Snub Cube',
                'summary': 'Chiral solid pairing squares with equilateral triangles.',
                'type': 'solid_viewer',
                'solid_id': 'snub_cube',
                'esoteric_description': ESOTERIC_DEFINITIONS['Snub Cube'],
            },
            {
                'name': 'Icosidodecahedron',
                'summary': 'Alternating pentagon-triangle faces bridging platonic duals.',
                'type': 'solid_viewer',
                'solid_id': 'icosidodecahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Icosidodecahedron'],
            },
            {
                'name': 'Truncated Dodecahedron',
                'summary': 'Decagon-triangle mixture carved from a dodecahedron.',
                'type': 'solid_viewer',
                'solid_id': 'truncated_dodecahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Truncated Dodecahedron'],
            },
            {
                'name': 'Truncated Icosahedron',
                'summary': 'Classic soccer-ball blend of pentagons and hexagons.',
                'type': 'solid_viewer',
                'solid_id': 'truncated_icosahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Truncated Icosahedron'],
            },
            {
                'name': 'Rhombicosidodecahedron',
                'summary': 'Uniform solid with 20 triangles, 30 squares, and 12 pentagons.',
                'type': 'solid_viewer',
                'solid_id': 'rhombicosidodecahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Rhombicosidodecahedron'],
            },
            {
                'name': 'Truncated Icosidodecahedron',
                'summary': 'Great rhombicosidodecahedron combining pentagons, decagons, and squares.',
                'type': 'solid_viewer',
                'solid_id': 'truncated_icosidodecahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Great Rhombicosidodecahedron'],
            },
            {
                'name': 'Snub Dodecahedron',
                'summary': 'Chiral pentagon-triangle solid completing the Archimedean family.',
                'type': 'solid_viewer',
                'solid_id': 'snub_dodecahedron',
                'esoteric_description': ESOTERIC_DEFINITIONS['Snub Dodecahedron'],
            },
        ],
    ),
    _category(
        name="Curves & Surfaces",
        icon="🌐",
        tagline="Sphere, Cylinder, Cone, Torus",
        shapes=[
            {
                'name': 'Sphere',
                'summary': 'Perfectly symmetrical solid with radius, area, and volume solving.',
                'type': 'solid_viewer',
                'solid_id': 'sphere',
                'esoteric_description': ESOTERIC_DEFINITIONS['Sphere'],
            },
            {
                'name': 'Cylinder',
                'summary': 'Right circular cylinder with caps and lateral surface metrics.',
                'type': 'solid_viewer',
                'solid_id': 'cylinder',
                'esoteric_description': ESOTERIC_DEFINITIONS['Cylinder'],
            },
            {
                'name': 'Cone',
                'summary': 'Right circular cone with base, apex height, and slant solvers.',
                'type': 'solid_viewer',
                'solid_id': 'cone',
                'esoteric_description': ESOTERIC_DEFINITIONS['Cone'],
            },
            {
                'name': 'Torus',
                'summary': 'Donut shape with major/minor radii, surface, and volume',
                'type': 'solid_viewer',
                'solid_id': 'torus',
                'esoteric_description': ESOTERIC_DEFINITIONS['Torus'],
            },
            {
                'name': 'Torus Knot',
                'summary': '(p, q) Torus Knot tube with customizable windings.',
                'type': 'solid_viewer',
                'solid_id': 'torus_knot',
                'esoteric_description': ESOTERIC_DEFINITIONS['Torus Knot'],
            },
        ],
    ),
    _category(
        name="Hypercube",
        icon="⧈",
        tagline="Dimensional expansions and projections",
        shapes=[
            {
                'name': 'Tesseract',
                'summary': 'Dual-cube Schlegel projection with 24 square faces.',
                'type': 'solid_viewer',
                'solid_id': 'tesseract',
            },
        ],
    ),
]

SOLID_VIEWER_CONFIG: Dict[str, dict] = {
    'tetrahedron': {
        'title': 'Tetrahedron',
        'summary': 'Edge-equal platonic solid with 4 faces, 6 edges, and 4 vertices.',
        'builder': TetrahedronSolidService.build,
        'calculator': TetrahedronSolidCalculator,
    },
    'cube': {
        'title': 'Cube',
        'summary': 'Six perfect squares with equal edges, diagonals, and orthogonal faces.',
        'builder': CubeSolidService.build,
        'calculator': CubeSolidCalculator,
    },
    'octahedron': {
        'title': 'Octahedron',
        'summary': 'Dual of the cube featuring eight equilateral triangles and axial symmetry.',
        'builder': OctahedronSolidService.build,
        'calculator': OctahedronSolidCalculator,
    },
    'dodecahedron': {
        'title': 'Dodecahedron',
        'summary': 'Twelve sacred pentagons with golden-ratio symmetry and rich radii.',
        'builder': DodecahedronSolidService.build,
        'calculator': DodecahedronSolidCalculator,
    },
    'icosahedron': {
        'title': 'Icosahedron',
        'summary': 'Twenty equilateral faces yielding maximal symmetry among platonic solids.',
        'builder': IcosahedronSolidService.build,
        'calculator': IcosahedronSolidCalculator,
    },
    'tesseract': {
        'title': 'Tesseract (Hypercube)',
        'summary': 'Schlegel projection of a four-dimensional cube with paired shells.',
        'builder': TesseractSolidService.build,
        'calculator': TesseractSolidCalculator,
    },
    'square_pyramid': {
        'title': 'Square Pyramid',
        'summary': 'Right square pyramid with interactive base + height driven metric coupling.',
        'builder': SquarePyramidSolidService.build,
        'calculator': SquarePyramidSolidCalculator,
    },
    'rectangular_pyramid': {
        'title': 'Rectangular Pyramid',
        'summary': 'Unequal base edges with dual slant heights and apex-controlled volume.',
        'builder': RectangularPyramidSolidService.build,
        'calculator': RectangularPyramidSolidCalculator,
    },
    'triangular_pyramid': {
        'title': 'Equilateral Triangular Pyramid',
        'summary': 'Regular triangle base with editable height, apothem, and slant relations.',
        'builder': TriangularPyramidSolidService.build,
        'calculator': TriangularPyramidSolidCalculator,
    },
    'pentagonal_pyramid': {
        'title': 'Regular Pentagonal Pyramid',
        'summary': 'Fivefold base pyramid highlighting apothem, lateral, and perimeter data.',
        'builder': PentagonalPyramidSolidService.build,
        'calculator': PentagonalPyramidSolidCalculator,
    },
    'hexagonal_pyramid': {
        'title': 'Regular Hexagonal Pyramid',
        'summary': 'Sixfold honeycomb base with full metric solving and 3D payload.',
        'builder': HexagonalPyramidSolidService.build,
        'calculator': HexagonalPyramidSolidCalculator,
    },
    'heptagonal_pyramid': {
        'title': 'Regular Heptagonal Pyramid',
        'summary': 'Sevenfold symmetry drive with detailed apothem, slant, and volume outputs.',
        'builder': HeptagonalPyramidSolidService.build,
        'calculator': HeptagonalPyramidSolidCalculator,
    },
    'square_pyramid_frustum': {
        'title': 'Square Pyramid Frustum',
        'summary': 'Truncated square pyramid with editable dual bases and slant-coupled metrics.',
        'builder': SquarePyramidFrustumSolidService.build,
        'calculator': SquarePyramidFrustumSolidCalculator,
    },
    'pentagonal_pyramid_frustum': {
        'title': 'Pentagonal Pyramid Frustum',
        'summary': 'Fivefold truncated pyramid with apothem-aware slant + volume solving.',
        'builder': PentagonalPyramidFrustumSolidService.build,
        'calculator': PentagonalPyramidFrustumSolidCalculator,
    },
    'hexagonal_pyramid_frustum': {
        'title': 'Hexagonal Pyramid Frustum',
        'summary': 'Sixfold honeycomb frustum with dual perimeters and metric coupling.',
        'builder': HexagonalPyramidFrustumSolidService.build,
        'calculator': HexagonalPyramidFrustumSolidCalculator,
    },
    'golden_pyramid': {
        'title': 'Golden Pyramid',
        'summary': 'Great Pyramid style square pyramid enforcing φ-based slant/height links.',
        'builder': GoldenPyramidSolidService.build,
        'calculator': GoldenPyramidSolidCalculator,
    },
    'step_pyramid': {
        'title': 'Step Pyramid',
        'summary': 'Adjustable terraced mastaba stack with tier-aware metrics.',
        'builder': StepPyramidSolidService.build,
        'calculator': StepPyramidSolidCalculator,
    },
    'rectangular_prism': {
        'title': 'Rectangular Prism',
        'summary': 'Axis-aligned box with independent length, width, height, and diagonal metrics.',
        'builder': RectangularPrismSolidService.build,
        'calculator': RectangularPrismSolidCalculator,
    },
    'triangular_prism': {
        'title': 'Triangular Prism',
        'summary': 'Equilateral base right prism featuring apothem, lateral area, and volume coupling.',
        'builder': TriangularPrismSolidService.build,
        'calculator': TriangularPrismSolidCalculator,
    },
    'pentagonal_prism': {
        'title': 'Pentagonal Prism',
        'summary': 'Fivefold regular prism with perimeter/apothem metrics and expansive surface data.',
        'builder': PentagonalPrismSolidService.build,
        'calculator': PentagonalPrismSolidCalculator,
    },
    'hexagonal_prism': {
        'title': 'Hexagonal Prism',
        'summary': 'Honeycomb-style regular prism highlighting lateral area and volume relationships.',
        'builder': HexagonalPrismSolidService.build,
        'calculator': HexagonalPrismSolidCalculator,
    },
    'heptagonal_prism': {
        'title': 'Heptagonal Prism',
        'summary': 'Sevenfold regular prism emphasizing perimeter/apothem coupling and volume.',
        'builder': HeptagonalPrismSolidService.build,
        'calculator': HeptagonalPrismSolidCalculator,
    },
    'octagonal_prism': {
        'title': 'Octagonal Prism',
        'summary': 'Stop-sign base prism with extended perimeter, apothem, and surface analytics.',
        'builder': OctagonalPrismSolidService.build,
        'calculator': OctagonalPrismSolidCalculator,
    },
    'oblique_prism': {
        'title': 'Oblique Prism',
        'summary': 'Regular prism sheared by a horizontal offset with edge and skew metrics.',
        'builder': ObliquePrismSolidService.build,
        'calculator': ObliquePrismSolidCalculator,
    },
    'prismatic_frustum': {
        'title': 'Prismatic Frustum',
        'summary': 'Truncated regular prism bridging distinct polygon edges with linear taper.',
        'builder': PrismaticFrustumSolidService.build,
        'calculator': PrismaticFrustumSolidCalculator,
    },
    'triangular_antiprism': {
        'title': 'Triangular Antiprism',
        'summary': 'Dual equilateral triangles rotated 60° and joined by six faces.',
        'builder': TriangularAntiprismSolidService.build,
        'calculator': TriangularAntiprismSolidCalculator,
    },
    'square_antiprism': {
        'title': 'Square Antiprism',
        'summary': 'Forty-five degree rotated squares creating an eight-triangle belt.',
        'builder': SquareAntiprismSolidService.build,
        'calculator': SquareAntiprismSolidCalculator,
    },
    'pentagonal_antiprism': {
        'title': 'Pentagonal Antiprism',
        'summary': 'Rotated pentagons producing a decagonal midsection with ten faces.',
        'builder': PentagonalAntiprismSolidService.build,
        'calculator': PentagonalAntiprismSolidCalculator,
    },
    'hexagonal_antiprism': {
        'title': 'Hexagonal Antiprism',
        'summary': 'Honeycomb antiprism featuring twelve lateral equilateral triangles.',
        'builder': HexagonalAntiprismSolidService.build,
        'calculator': HexagonalAntiprismSolidCalculator,
    },
    'octagonal_antiprism': {
        'title': 'Octagonal Antiprism',
        'summary': 'Stop-sign antiprism with sixteen congruent triangle faces.',
        'builder': OctagonalAntiprismSolidService.build,
        'calculator': OctagonalAntiprismSolidCalculator,
    },
    'heptagonal_antiprism': {
        'title': 'Heptagonal Antiprism',
        'summary': 'Sevenfold antiprism forming fourteen lateral equilateral triangles.',
        'builder': HeptagonalAntiprismSolidService.build,
        'calculator': HeptagonalAntiprismSolidCalculator,
    },
    'truncated_tetrahedron': {
        'title': 'Truncated Tetrahedron',
        'summary': 'Four hexagons and four triangles derived from a sliced tetrahedron.',
        'builder': TruncatedTetrahedronSolidService.build,
        'calculator': TruncatedTetrahedronSolidCalculator,
    },
    'cuboctahedron': {
        'title': 'Cuboctahedron',
        'summary': 'Uniform solid blending cube and octahedron symmetries.',
        'builder': CuboctahedronSolidService.build,
        'calculator': CuboctahedronSolidCalculator,
    },
    'truncated_cube': {
        'title': 'Truncated Cube',
        'summary': 'Eight triangles and six octagons from shaving cube corners.',
        'builder': TruncatedCubeSolidService.build,
        'calculator': TruncatedCubeSolidCalculator,
    },
    'truncated_octahedron': {
        'title': 'Truncated Octahedron',
        'summary': 'Space-filling Archimedean solid mixing squares and hexagons.',
        'builder': TruncatedOctahedronSolidService.build,
        'calculator': TruncatedOctahedronSolidCalculator,
    },
    'rhombicuboctahedron': {
        'title': 'Rhombicuboctahedron',
        'summary': 'Eighteen squares and eight triangles arranged with uniform edges.',
        'builder': RhombicuboctahedronSolidService.build,
        'calculator': RhombicuboctahedronSolidCalculator,
    },
    'truncated_cuboctahedron': {
        'title': 'Truncated Cuboctahedron',
        'summary': 'Great rhombicuboctahedron weaving hexagons, squares, and octagons.',
        'builder': TruncatedCuboctahedronSolidService.build,
        'calculator': TruncatedCuboctahedronSolidCalculator,
    },
    'snub_cube': {
        'title': 'Snub Cube',
        'summary': 'Chiral Archimedean solid pairing squares with equilateral triangles.',
        'builder': SnubCubeSolidService.build,
        'calculator': SnubCubeSolidCalculator,
    },
    'icosidodecahedron': {
        'title': 'Icosidodecahedron',
        'summary': 'Alternating pentagon-triangle faces bridging platonic duals.',
        'builder': IcosidodecahedronSolidService.build,
        'calculator': IcosidodecahedronSolidCalculator,
    },
    'truncated_dodecahedron': {
        'title': 'Truncated Dodecahedron',
        'summary': 'Decagon-triangle mixture carved from a dodecahedron.',
        'builder': TruncatedDodecahedronSolidService.build,
        'calculator': TruncatedDodecahedronSolidCalculator,
    },
    'truncated_icosahedron': {
        'title': 'Truncated Icosahedron',
        'summary': 'Soccer-ball blend of twelve pentagons and twenty hexagons.',
        'builder': TruncatedIcosahedronSolidService.build,
        'calculator': TruncatedIcosahedronSolidCalculator,
    },
    'rhombicosidodecahedron': {
        'title': 'Rhombicosidodecahedron',
        'summary': 'Uniform solid with triangles, squares, and pentagons in harmony.',
        'builder': RhombicosidodecahedronSolidService.build,
        'calculator': RhombicosidodecahedronSolidCalculator,
    },
    'truncated_icosidodecahedron': {
        'title': 'Truncated Icosidodecahedron',
        'summary': 'Great rhombicosidodecahedron combining pentagons, decagons, and squares.',
        'builder': TruncatedIcosidodecahedronSolidService.build,
        'calculator': TruncatedIcosidodecahedronSolidCalculator,
    },
    'snub_dodecahedron': {
        'title': 'Snub Dodecahedron',
        'summary': 'Chiral pentagon-triangle solid completing the Archimedean family.',
        'builder': SnubDodecahedronSolidService.build,
        'calculator': SnubDodecahedronSolidCalculator,
    },
    'torus': {
        'title': 'Torus',
        'summary': 'Ring-shaped surface of revolution generated by a circle.',
        'builder': TorusSolidService.build,
        'calculator': TorusSolidCalculator,
    },
    'torus_knot': {
        'title': 'Torus Knot',
        'summary': 'Intertwined tube wrapping around a torus surface.',
        'builder': TorusKnotSolidService.build,
        'calculator': TorusKnotSolidCalculator,
    },
    'vault_of_hestia_3d': {
        'title': 'Vault of Hestia (3D)',
        'summary': 'Cube holding a Pyramid holding a Sphere (Phi Generator).',
        'builder': VaultOfHestiaSolidService.build,
        'calculator': VaultOfHestiaSolidCalculator,
    },
    'sphere': {
        'title': 'Sphere',
        'summary': 'A perfectly symmetrical 3D surface where every point is equidistant from the center.',
        'builder': SphereSolidService.build,
        'calculator': SphereSolidCalculator,
    },
    'cylinder': {
        'title': 'Cylinder',
        'summary': 'A solid with two identical circular bases connected by a curved lateral surface.',
        'builder': CylinderSolidService.build,
        'calculator': CylinderSolidCalculator,
    },
    'cone': {
        'title': 'Cone',
        'summary': 'A solid that tapers smoothly from a flat circular base to a single point called the apex.',
        'builder': ConeSolidService.build,
        'calculator': ConeSolidCalculator,
    },
    'general_prism': {
        'title': 'General Prism',
        'summary': 'A customizable right prism with an n-gonal regular base.',
        'builder': GeneralPrismSolidService.build_dynamic,
        'calculator': GeneralPrismSolidCalculator,
    },
    'general_pyramid': {
        'title': 'General Pyramid',
        'summary': 'A customizable right pyramid with an n-gonal regular base.',
        'builder': GeneralPyramidSolidService.build_dynamic,
        'calculator': GeneralPyramidSolidCalculator,
    },
    'general_antiprism': {
        'title': 'General Antiprism',
        'summary': 'A customizable right antiprism with an n-gonal regular base.',
        'builder': GeneralAntiprismSolidService.build_dynamic,
        'calculator': GeneralAntiprismSolidCalculator,
    },
    'gyro_square_prism': {
        'title': 'Gyroelongated Square Prism',
        'summary': 'A square prism with a square antiprism section attached.',
        'builder': GyroelongatedSquarePrismSolidService.build,
        'calculator': GyroelongatedSquarePrismSolidCalculator,
    },
    'snub_square_antiprism': {
        'title': 'Snub Square Antiprism (J85)',
        'summary': 'A complex Johnson solid (J85) with 24 triangular faces and 2 square faces.',
        'builder': SnubAntiprismSolidService.build,
        'calculator': SnubAntiprismSolidCalculator,
    },
    'twisted_icosahedral_antiprism': {
        'title': 'Twisted Icosahedral Antiprism',
        'summary': 'A decagonal (n=10) antiprism representing high-order prismatic twisting.',
        'builder': lambda **kwargs: GeneralAntiprismSolidService.build_dynamic(sides=10, **kwargs),
        'calculator': lambda **kwargs: GeneralAntiprismSolidCalculator(sides=10, **kwargs),
    },
}
