from PyQt5.QtWidgets import (QDialog, QVBoxLayout, QGraphicsView, QGraphicsScene, 
                            QWidget, QToolBar, QPushButton, QComboBox, QGraphicsItem,
                            QGraphicsEllipseItem, QGraphicsLineItem, QMenu)
from PyQt5.QtCore import Qt, QPointF, QRectF
from PyQt5.QtGui import QPen, QColor, QPainter, QBrush, QKeySequence
import math
import time
from dataclasses import dataclass, field
from typing import Optional, Set, Dict, List, Tuple

class GeometryLine(QGraphicsLineItem):
    """A custom line item that can be selected and styled based on its type.
    
    Types:
        BASE: Structural lines that form the basic geometry (non-selectable)
        PATTERN: Lines generated by pattern algorithms
        CUSTOM: User-drawn lines
    
    Attributes:
        line_type: The type of line (BASE, PATTERN, or CUSTOM)
    """
    
    class Type:
        """Enumeration of line types"""
        BASE = 1    # Structural lines (polygon/star base)
        PATTERN = 2 # Generated from patterns
        CUSTOM = 3  # User-drawn

    def __init__(self, x1, y1, x2, y2, line_type, parent=None):
        super().__init__(x1, y1, x2, y2, parent)
        self.line_type = line_type
        self.start_num = None  # Store point numbers
        self.end_num = None
        self.setAcceptHoverEvents(True)
        self.setFlag(QGraphicsItem.ItemIsSelectable, False)
        self.setFlag(QGraphicsItem.ItemIsFocusable, True)
        
        # Set lower Z value for lines
        self.setZValue(1)  # Lines stay above background but below points
        
        # Set appearance based on type
        if line_type == self.Type.BASE:
            self.setPen(QPen(QColor(70, 130, 180), 2))
        elif line_type == self.Type.PATTERN:
            self.setPen(QPen(QColor(255, 165, 0), 2))
        else:  # CUSTOM
            self.setPen(QPen(QColor(255, 165, 0), 4))

    @classmethod
    def from_points(cls, start_pos, end_pos, line_type):
        """Create a line from two QPointF objects.
        
        Args:
            start_pos (QPointF): Starting point of the line
            end_pos (QPointF): Ending point of the line
            line_type (Type): Type of line to create
            
        Returns:
            GeometryLine: New line instance
        """
        return cls(
            start_pos.x(), start_pos.y(),
            end_pos.x(), end_pos.y(),
            line_type
        )

    def mousePressEvent(self, event):
        """Handle mouse press on the line"""
        if event.button() == Qt.LeftButton:
            # Let the view handle the selection
            view = self.scene().views()[0]
            view.handle_line_click(self, event)
            event.accept()
        else:
            super().mousePressEvent(event)

    def set_endpoints(self, start_num, end_num):
        """Store the point numbers this line connects"""
        self.start_num = start_num
        self.end_num = end_num

@dataclass
class Point:
    """Represents a point in the geometry system"""
    item: QGraphicsEllipseItem
    position: QPointF
    number: int
    connections: Set[int] = field(default_factory=set)  # Connected point numbers

@dataclass
class Line:
    """Represents a line in the geometry system"""
    item: GeometryLine
    start: int  # Point number
    end: int    # Point number
    type: int   # Line type

class SpatialGrid:
    """Optimized spatial partitioning system"""
    def __init__(self, cell_size: int = 50, bounds: QRectF = None):
        self.cell_size = cell_size
        self.points: Dict[Tuple[int, int], List[Point]] = {}
        self.lines: Dict[Tuple[int, int], List[Line]] = {}
        self.point_lookup: Dict[int, Point] = {}  # number -> Point
        self.line_lookup: Dict[Tuple[int, int], Line] = {}  # (start, end) -> Line
        
        # Add QuadTree for points and lines
        self.point_tree = QuadTree(bounds or QRectF(-1000, -1000, 2000, 2000))
        self.line_tree = QuadTree(bounds or QRectF(-1000, -1000, 2000, 2000))
        
    def get_cell(self, pos: QPointF) -> Tuple[int, int]:
        """Get cell coordinates for a position"""
        return (int(pos.x() // self.cell_size), 
                int(pos.y() // self.cell_size))

    def add_point(self, point: Point) -> None:
        """Add a point to the grid"""
        cell = self.get_cell(point.position)
        if cell not in self.points:
            self.points[cell] = []
        self.points[cell].append(point)
        self.point_lookup[point.number] = point
        
        # Add to QuadTree
        bounds = QRectF(point.position.x() - 5, point.position.y() - 5, 10, 10)
        self.point_tree.insert(point, bounds)

    def add_line(self, line: Line, bounds: QRectF) -> None:
        """Add a line to all cells it intersects"""
        # Get all cells the line's bounding box intersects
        min_cell = self.get_cell(bounds.topLeft())
        max_cell = self.get_cell(bounds.bottomRight())
        
        # Debug output
        print(f"Adding line to cells from {min_cell} to {max_cell}")
        
        for x in range(min_cell[0], max_cell[0] + 1):
            for y in range(min_cell[1], max_cell[1] + 1):
                cell = (x, y)
                if cell not in self.lines:
                    self.lines[cell] = []
                self.lines[cell].append(line)
                print(f"Added line to cell {cell}")

    def remove_line(self, line: Line) -> None:
        """Remove a line from the grid"""
        # Remove from cells
        for cell_lines in self.lines.values():
            if line in cell_lines:
                cell_lines.remove(line)
        
        # Remove from lookups
        self.line_lookup.pop((line.start, line.end), None)
        self.line_lookup.pop((line.end, line.start), None)
        
        # Update point connections
        self.point_lookup[line.start].connections.remove(line.end)
        self.point_lookup[line.end].connections.remove(line.start)

    def get_nearby_items(self, pos: QPointF, radius: float) -> Tuple[List[Point], List[Line]]:
        """Get all items within radius of position"""
        center_cell = self.get_cell(pos)
        cell_radius = int(radius // self.cell_size) + 1
        
        nearby_points: List[Point] = []
        nearby_lines: List[Line] = []
        checked_cells: Set[Tuple[int, int]] = set()
        
        # Check cells in radius
        for dx in range(-cell_radius, cell_radius + 1):
            for dy in range(-cell_radius, cell_radius + 1):
                cell = (center_cell[0] + dx, center_cell[1] + dy)
                if cell in checked_cells:
                    continue
                    
                checked_cells.add(cell)
                if cell in self.points:
                    nearby_points.extend(self.points[cell])
                if cell in self.lines:
                    nearby_lines.extend(self.lines[cell])
        
        return nearby_points, nearby_lines

    def get_line_cells(self, start: QPointF, end: QPointF) -> Set[Tuple[int, int]]:
        """Get all grid cells that a line passes through using DDA algorithm"""
        cells = set()
        start_cell = self.get_cell(start)
        end_cell = self.get_cell(end)
        
        dx = end_cell[0] - start_cell[0]
        dy = end_cell[1] - start_cell[1]
        steps = max(abs(dx), abs(dy))
        
        if steps == 0:
            return {start_cell}
            
        x_inc = dx / steps
        y_inc = dy / steps
        
        x, y = start_cell
        for _ in range(steps + 1):
            cells.add((int(x), int(y)))
            x += x_inc
            y += y_inc
        
        return cells

    def is_connected(self, point1: int, point2: int) -> bool:
        """Check if two points are connected"""
        return point2 in self.point_lookup[point1].connections

    def get_point(self, number: int) -> Optional[Point]:
        """Get point by number"""
        return self.point_lookup.get(number)

    def get_line(self, start: int, end: int) -> Optional[Line]:
        """Get line by endpoint numbers"""
        return self.line_lookup.get((start, end))

class QuadTree:
    """Spatial indexing for faster item lookup"""
    def __init__(self, bounds, max_items=10, max_depth=6):
        self.bounds = bounds  # QRectF
        self.max_items = max_items
        self.max_depth = max_depth
        self.items = []
        self.children = []
        self.depth = 0
        
    def subdivide(self):
        """Split node into four children"""
        x = self.bounds.x()
        y = self.bounds.y()
        w = self.bounds.width() / 2
        h = self.bounds.height() / 2
        
        self.children = [
            QuadTree(QRectF(x, y, w, h), self.max_items, self.max_depth),
            QuadTree(QRectF(x + w, y, w, h), self.max_items, self.max_depth),
            QuadTree(QRectF(x, y + h, w, h), self.max_items, self.max_depth),
            QuadTree(QRectF(x + w, y + h, w, h), self.max_items, self.max_depth)
        ]
        for child in self.children:
            child.depth = self.depth + 1

    def insert(self, item, bounds):
        """Insert item with its bounds"""
        if not self.bounds.intersects(bounds):
            return False
            
        if len(self.children) == 0:
            if len(self.items) < self.max_items or self.depth >= self.max_depth:
                self.items.append((item, bounds))
                return True
            else:
                self.subdivide()
                
        # Try to insert into children
        for child in self.children:
            if child.insert(item, bounds):
                return True
                
        # If couldn't insert into children, keep in current node
        self.items.append((item, bounds))
        return True

    def query(self, search_bounds):
        """Find all items intersecting search bounds"""
        found_items = []
        
        if not self.bounds.intersects(search_bounds):
            return found_items
            
        # Check items at this level
        for item, bounds in self.items:
            if bounds.intersects(search_bounds):
                found_items.append(item)
                
        # Check children
        for child in self.children:
            found_items.extend(child.query(search_bounds))
            
        return found_items

class GeometryScene(QGraphicsScene):
    """Scene that handles clicks to draw lines between points."""
    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent_widget = parent
        self.last_clicked_point = None
        self.drawing_mode = True
        self.preview_line = None
        
    def mousePressEvent(self, event):
        """Handle mouse press events for point/line selection and line drawing."""
        scene_pos = event.scenePos()
        items = self.items(scene_pos)
        
        if not items:
            # Clicked empty space - clear selection
            self.clearSelection()
            self.last_clicked_point = None
            super().mousePressEvent(event)
            return
            
        top_item = items[0]
        
        if isinstance(top_item, GeometryPoint):
            self.handle_point_click(top_item, event)
        elif isinstance(top_item, GeometryLine):
            self.handle_line_click(top_item, event)
        else:
            super().mousePressEvent(event)
            
    def handle_point_click(self, point, event):
        """Handle clicks on points."""
        if not self.drawing_mode:
            super().mousePressEvent(event)
            return
            
        if self.last_clicked_point is None:
            # Start drawing a line
            self.last_clicked_point = point
            point.setBrush(QBrush(QColor("red")))  # Visual feedback
            
            # Create preview line
            pos = point.scenePos()
            self.preview_line = self.addLine(
                pos.x(), pos.y(), pos.x(), pos.y(),
                QPen(QColor("gray"), 2, Qt.DashLine)
            )
        else:
            if point != self.last_clicked_point:
                # Complete the line
                self.create_line(self.last_clicked_point, point)
                
            # Reset state
            self.last_clicked_point.setBrush(QBrush(QColor("dodgerblue")))
            if self.preview_line:
                self.removeItem(self.preview_line)
                self.preview_line = None
            self.last_clicked_point = None
            
    def handle_line_click(self, line, event):
        """Handle clicks on lines."""
        if self.drawing_mode:
            return  # Ignore line clicks in drawing mode
            
        if event.modifiers() == Qt.ControlModifier:
            # Multi-select with Ctrl
            line.setSelected(not line.isSelected())
        else:
            # Single select
            self.clearSelection()
            line.setSelected(True)
            
    def mouseMoveEvent(self, event):
        """Update preview line during drawing."""
        if self.preview_line and self.last_clicked_point:
            start_pos = self.last_clicked_point.scenePos()
            end_pos = event.scenePos()
            self.preview_line.setLine(
                start_pos.x(), start_pos.y(),
                end_pos.x(), end_pos.y()
            )
        super().mouseMoveEvent(event)
        
    def create_line(self, start_point, end_point):
        """Create a new line between points."""
        start_pos = start_point.scenePos()
        end_pos = end_point.scenePos()
        
        line = GeometryLine.from_points(
            start_pos, end_pos,
            GeometryLine.Type.CUSTOM
        )
        line.set_endpoints(start_point.number, end_point.number)
        self.addItem(line)
        
        if self.parent_widget:
            self.parent_widget.custom_lines.append(line)
            
        return line

class GeometryVisualizerView(QGraphicsView):
    """View that handles zooming and general interaction."""
    def __init__(self, scene, parent=None):
        super().__init__(scene, parent)
        self.parent_widget = parent
        
        # Setup view properties
        self.setRenderHint(QPainter.Antialiasing)
        self.setViewportUpdateMode(QGraphicsView.FullViewportUpdate)
        self.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.setTransformationAnchor(QGraphicsView.AnchorUnderMouse)
        self.setResizeAnchor(QGraphicsView.AnchorUnderMouse)
        
        # Initialize state
        self.setDragMode(QGraphicsView.RubberBandDrag)
        self.zoom_factor = 1.15
        self.drawing_mode = True

    def set_drawing_mode(self, enabled):
        """Update drawing mode and cursor"""
        self.drawing_mode = enabled
        if enabled:
            self.setDragMode(QGraphicsView.NoDrag)
            self.setCursor(Qt.CrossCursor)
        else:
            self.setDragMode(QGraphicsView.ScrollHandDrag)
            self.setCursor(Qt.ArrowCursor)
            
    def handle_line_click(self, line, event):
        """Handle clicks on lines"""
        if self.drawing_mode:
            return  # Ignore line clicks in drawing mode
            
        if event.modifiers() == Qt.ControlModifier:
            # Multi-select with Ctrl
            line.setSelected(not line.isSelected())
        else:
            # Single select
            self.scene().clearSelection()
            line.setSelected(True)
            
    def wheelEvent(self, event):
        """Handle zooming with mouse wheel."""
        if event.modifiers() == Qt.ControlModifier:
            if event.angleDelta().y() > 0:
                self.scale(self.zoom_factor, self.zoom_factor)
            else:
                self.scale(1 / self.zoom_factor, 1 / self.zoom_factor)
            event.accept()
        else:
            super().wheelEvent(event)
            
    def keyPressEvent(self, event):
        """Handle keyboard shortcuts."""
        if event.key() == Qt.Key_Space:
            # Toggle drag mode
            if self.dragMode() == QGraphicsView.RubberBandDrag:
                self.setDragMode(QGraphicsView.ScrollHandDrag)
            else:
                self.setDragMode(QGraphicsView.RubberBandDrag)
        else:
            super().keyPressEvent(event)

class GeometryVisualizerContent(QWidget):
    """Main widget for visualizing geometric patterns and handling user interactions.
    
    This widget provides tools for:
    - Drawing polygonal/star patterns
    - Adding custom lines between points
    - Applying predefined patterns
    - Managing line selections and modifications
    
    Attributes:
        number_type (str): Type of number visualization ('star' or 'polygon')
        n_points (int): Number of points in the base shape
        position (int): Position/layer count in the visualization
    """
    def __init__(self, parent=None):
        super().__init__(parent)
        self.parent_widget = parent
        
        # Setup layout
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        
        # Create toolbar
        self.toolbar = QToolBar()
        self.setup_toolbar()
        layout.addWidget(self.toolbar)
        
        # Create scene and view
        self.scene = GeometryScene(self)
        self.view = GeometryVisualizerView(self.scene, self)
        
        # Set scene rect to ensure items are visible
        self.scene.setSceneRect(-200, -200, 400, 400)
        
        # Add view to layout
        layout.addWidget(self.view)
        
        # Initialize state
        self.drawing_mode = True
        self.custom_lines = []
        self.pattern_lines = []
        self.selected_lines = set()
        
        # Setup undo/redo
        self.undo_stack = []
        self.redo_stack = []
        
        # Create test points to verify visualization
        self.create_test_points()

    def setup_toolbar(self):
        # Drawing mode toggle
        self.draw_mode_btn = QPushButton("Draw Mode")
        self.draw_mode_btn.setCheckable(True)
        self.draw_mode_btn.setChecked(True)
        self.draw_mode_btn.clicked.connect(self.toggle_drawing_mode)
        self.toolbar.addWidget(self.draw_mode_btn)
        
        # Delete button
        self.delete_btn = QPushButton("Delete Selected")
        self.delete_btn.clicked.connect(self.delete_selected)
        self.toolbar.addWidget(self.delete_btn)
        
        # Undo/Redo buttons
        self.undo_btn = QPushButton("Undo")
        self.redo_btn = QPushButton("Redo")
        self.undo_btn.clicked.connect(self.undo_last_action)
        self.redo_btn.clicked.connect(self.redo_last_action)
        self.toolbar.addWidget(self.undo_btn)
        self.toolbar.addWidget(self.redo_btn)

    def create_point(self, x, y, number):
        """Create a new point in the scene"""
        point = GeometryPoint(x, y, number)
        self.scene.addItem(point)
        return point

    def create_line(self, start_point, end_point, line_type=GeometryLine.Type.CUSTOM):
        """Create a new line between points"""
        # Get the center positions of the points
        start_pos = start_point.scenePos()
        end_pos = end_point.scenePos()
        
        # Create line using class method
        line = GeometryLine.from_points(
            start_pos,
            end_pos,
            line_type
        )
        
        # Set endpoint numbers
        line.set_endpoints(start_point.number, end_point.number)
        
        # Add to scene
        self.scene.addItem(line)
        
        # Add to appropriate collection
        if line_type == GeometryLine.Type.CUSTOM:
            self.custom_lines.append(line)
        elif line_type == GeometryLine.Type.PATTERN:
            self.pattern_lines.append(line)
            
        # Add to undo stack
        self.undo_stack.append({
            'type': 'create_line',
            'line': line,
            'start': start_point.number,
            'end': end_point.number
        })
        self.redo_stack.clear()
        
        return line

    def delete_selected(self):
        """Delete selected lines"""
        if not self.selected_lines:
            return
            
        # Store for undo
        undo_action = {
            'type': 'delete',
            'lines': [(line, line.line_type) for line in self.selected_lines]
        }
        
        # Remove lines
        for line in self.selected_lines:
            if line in self.custom_lines:
                self.custom_lines.remove(line)
            elif line in self.pattern_lines:
                self.pattern_lines.remove(line)
            self.scene.removeItem(line)
            
        self.selected_lines.clear()
        self.undo_stack.append(undo_action)
        self.redo_stack.clear()

    def toggle_drawing_mode(self, checked):
        """Toggle drawing mode"""
        self.drawing_mode = checked
        self.view.set_drawing_mode(checked)
        self.draw_mode_btn.setText("Drawing Mode (On)" if checked else "Drawing Mode")

    def undo_last_action(self):
        """Undo last line action"""
        if not self.undo_stack:
            return
            
        action = self.undo_stack.pop()
        if action['type'] == 'delete':
            redo_action = {
                'type': 'delete',
                'lines': []
            }
            
            # Recreate each line with all its properties
            for line_info in action['lines']:
                geom = line_info['geometry']
                new_line = GeometryLine(
                    geom.x1(), geom.y1(),
                    geom.x2(), geom.y2(),
                    line_info['line_type']
                )
                new_line.set_endpoints(line_info['start'], line_info['end'])
                
                # Add to scene and collections
                self.scene.addItem(new_line)
                if line_info['line_type'] == GeometryLine.Type.CUSTOM:
                    self.custom_lines.append(new_line)
                elif line_info['line_type'] == GeometryLine.Type.PATTERN:
                    self.pattern_lines.append(new_line)
                
                # Restore connection tracking
                connection = tuple(sorted([line_info['start'], line_info['end']]))
                self.connected_points.add(connection)
                
                # Store for redo
                redo_action['lines'].append({
                    'geometry': geom,
                    'start': line_info['start'],
                    'end': line_info['end'],
                    'line_type': line_info['line_type']
                })
            
            self.redo_stack.append(redo_action)

    def redo_last_action(self):
        """Redo last undone action"""
        if not self.redo_stack:
            return
            
        action = self.redo_stack.pop()
        if action['type'] == 'delete':
            # Re-delete the lines
            undo_action = {
                'type': 'delete',
                'lines': valid_lines,  # Just store the valid lines directly
                'connections': action.get('connections', [])  # Get connections with default empty list
            }
            
            for line, _ in action['lines']:
                if line in self.selected_lines:
                    self.selected_lines.remove(line)
                self.custom_lines.remove(line)
                self.scene.removeItem(line)
            
            # Re-add connections
            for connection in action['connections']:
                start_num, end_num = connection
                line = GeometryLine.from_points(
                    QPointF(0, 0),
                    QPointF(0, 0),
                    GeometryLine.Type.CUSTOM
                )
                line.set_endpoints(start_num, end_num)
                self.custom_lines.append(line)
            
            self.undo_stack.append(undo_action)

    def handle_line_click(self, line, event):
        """Handle mouse clicks on lines.
        
        Manages line selection behavior:
        - Ctrl+click for multiple selection
        - Single click for single selection
        - Updates line appearance based on selection state
        
        Args:
            line (GeometryLine): The clicked line
            event (QMouseEvent): The mouse event
        """
        if not self.drawing_mode and line in self.parent_widget.selectable_lines:
            if event.modifiers() == Qt.ControlModifier:
                if line in self.selected_lines:
                    self.selected_lines.remove(line)
                    self.restore_line_appearance(line)
                else:
                    self.selected_lines.add(line)
                    line.setPen(QPen(self.line_selected_color, 4))
            else:
                for selected_line in self.selected_lines:
                    self.restore_line_appearance(selected_line)
                self.selected_lines.clear()
                self.selected_lines.add(line)
                line.setPen(QPen(self.line_selected_color, 4))

    def restore_line_appearance(self, line):
        """Restore original line appearance based on line type"""
        if isinstance(line, GeometryLine):
            if line.line_type == GeometryLine.Type.PATTERN:
                line.setPen(QPen(QColor(255, 165, 0), 2))  # Orange, normal width
            elif line.line_type == GeometryLine.Type.CUSTOM:
                line.setPen(QPen(QColor(255, 165, 0), 4))  # Orange, thicker
            # Base lines shouldn't need restoration as they can't be selected

    def draw_connection(self):
        """Draw line between selected points"""
        if len(self.selected_points) != 2:
            return
            
        start_item, start_num = self.selected_points[0]
        end_item, end_num = self.selected_points[1]
        
        start_pos = start_item.sceneBoundingRect().center()
        end_pos = end_item.sceneBoundingRect().center()
        
        line = GeometryLine.from_points(
            start_pos,
            end_pos,
            GeometryLine.Type.CUSTOM
        )
        if self.custom_lines is not None:  # Check if collection is available
            self.custom_lines.append(line)

    def show_line_context_menu(self, pos, line):
        """Show context menu for line"""
        menu = QMenu()
        
        delete_action = menu.addAction("Delete Line")
        delete_action.triggered.connect(lambda: self.delete_selected_lines([line]))
        
        if len(self.selected_lines) > 1:
            delete_all_action = menu.addAction(f"Delete Selected Lines ({len(self.selected_lines)})")
            delete_all_action.triggered.connect(lambda: self.delete_selected_lines(self.selected_lines))
        
        menu.exec_(pos)

    def delete_selected_lines(self, lines):
        """Delete selected lines with undo support"""
        try:
            valid_lines = []
            for line in lines:
                if line.scene() == self.scene:
                    valid_lines.append({
                        'geometry': line.line(),
                        'start_num': line.start_num,
                        'end_num': line.end_num,
                        'line_type': line.line_type,
                        'original': line
                    })
            
            if not valid_lines:
                return
                
            undo_action = {
                'type': 'delete',
                'lines': valid_lines
            }
            
            # Remove lines and update connection manager
            for line_info in valid_lines:
                line = line_info['original']
                if line in self.selected_lines:
                    self.selected_lines.remove(line)
                if line in self.custom_lines:
                    self.custom_lines.remove(line)
                
                # Remove from connection manager
                self.connection_manager.remove_connection(
                    line_info['start_num'],
                    line_info['end_num']
                )
                
                self.scene.removeItem(line)
            
            self.undo_stack.append(undo_action)
            self.redo_stack.clear()
            
        except Exception as e:
            print(f"Error deleting lines: {str(e)}")

    def set_drawing_mode(self, enabled):
        """Update drawing mode and cursor"""
        self.drawing_mode = enabled
        if enabled:
            self.setDragMode(QGraphicsView.NoDrag)
            self.setCursor(Qt.CrossCursor)
        else:
            self.setDragMode(QGraphicsView.ScrollHandDrag)
            self.setCursor(Qt.ArrowCursor)
            # Clean up any in-progress drawing
            if self.preview_line:
                self.scene.removeItem(self.preview_line)
                self.preview_line = None
            self.drawing_line = False
            self.start_point = None

    def restore_point_appearance(self, item):
        """Restore original point appearance"""
        item.setBrush(QBrush(self.parent_widget.dot_color))
        item.setPen(QPen(self.parent_widget.dot_color))

    def keyPressEvent(self, event):
        """Handle key events"""
        if event.key() == Qt.Key_Delete and self.selected_lines:
            self.delete_selected_lines(self.selected_lines)
        elif event.matches(QKeySequence.Undo):
            self.undo_last_action()
        elif event.matches(QKeySequence.Redo):
            self.redo_last_action()
        else:
            super().keyPressEvent(event)

    def cleanup_drawing_state(self):
        """Clean up the drawing state"""
        if self.preview_line:
            self.scene.removeItem(self.preview_line)
            self.preview_line = None
        
        if self.start_point:
            self.restore_point_appearance(self.start_point)
        if self.snap_target:
            self.restore_point_appearance(self.snap_target)
        
        self.drawing_line = False
        self.start_point = None
        self.snap_target = None

    def handle_point_click(self, clicked_point):
        """Handle clicks on points when in drawing mode.
        
        Args:
            clicked_point: The QGraphicsEllipseItem that was clicked
        """
        if not self.drawing_line:
            # Start drawing a line
            self.drawing_line = True
            self.start_point = clicked_point
            start_pos = clicked_point.sceneBoundingRect().center()
            
            # Visual feedback
            clicked_point.setBrush(QBrush(self.snap_color))
            
            # Create preview line
            self.preview_line = self.scene.addLine(
                start_pos.x(), start_pos.y(),
                start_pos.x(), start_pos.y(),
                QPen(self.preview_color, 2, Qt.DashLine)
            )

    def add_points_bulk(self, points):
        """Add multiple points efficiently"""
        for point in points:
            self.spatial_grid.add_point(point)
            
        # Batch scene updates
        self.scene.update()
        
    def add_lines_bulk(self, lines):
        """Add multiple lines efficiently"""
        for line in lines:
            self.spatial_grid.add_line(line)
            
        self.scene.update()
        
    def delete_lines_bulk(self, lines):
        """Delete multiple lines efficiently"""
        updates = []
        for line in lines:
            # Collect all updates
            updates.append({
                'line': line,
                'connections': self.get_line_connections(line)
            })
            
        # Perform updates in batch
        with self.batch_updates():
            for update in updates:
                self.remove_line(update['line'])
                self.remove_connections(update['connections'])

    def create_test_points(self):
        """Create some test points to verify the visualization is working"""
        # Create a square of points
        points = [
            (0, 0, 1),
            (100, 0, 2),
            (100, 100, 3),
            (0, 100, 4)
        ]
        
        for x, y, num in points:
            self.create_point(x, y, num)

    def create_polygon(self, sides, center=None):
        """Create a regular polygon in the scene"""
        if center is None:
            center = QPointF(0, 0)
            
        radius = 100
        points = []
        
        # Create points
        for i in range(sides):
            angle = 2 * math.pi * i / sides
            x = center.x() + radius * math.cos(angle)
            y = center.y() + radius * math.sin(angle)
            point = self.create_point(x, y, i + 1)
            points.append(point)
            
        # Create lines
        for i in range(sides):
            start = points[i]
            end = points[(i + 1) % sides]
            self.create_line(start, end, GeometryLine.Type.BASE)
            
        return points

class LineCreationError(Exception):
    """Custom exception for line creation failures"""
    pass

class GeometryConnectionManager:
    """Manages geometric connections between points.
    
    Tracks:
    - Point-to-point connections
    - Connection metadata (type, creation time, properties)
    - Connection history
    - Connection patterns
    """
    def __init__(self):
        self.connections = {}  # Graph structure: point_num -> {connected_point: line_ref}
        self.connection_metadata = {}  # (point1, point2) -> metadata
        self.connection_history = []  # List of (action, point1, point2, metadata)
        
    def add_connection(self, start_num, end_num, line_type, line_ref):
        """Add a new connection with metadata"""
        # Ensure points are ordered consistently
        point1, point2 = sorted([start_num, end_num])
        
        # Initialize connection points if needed
        if point1 not in self.connections:
            self.connections[point1] = {}
        if point2 not in self.connections:
            self.connections[point2] = {}
            
        # Add bidirectional connection
        self.connections[point1][point2] = line_ref
        self.connections[point2][point1] = line_ref
        
        # Store metadata
        metadata = {
            'type': line_type,
            'created_at': time.time(),
            'line_ref': line_ref
        }
        self.connection_metadata[(point1, point2)] = metadata
        
        # Record in history
        self.connection_history.append(('add', point1, point2, metadata))
        
    def remove_connection(self, start_num, end_num):
        """Remove a connection and update history"""
        point1, point2 = sorted([start_num, end_num])
        
        if point1 in self.connections and point2 in self.connections[point1]:
            # Record in history before removing
            metadata = self.connection_metadata.get((point1, point2), {})
            self.connection_history.append(('remove', point1, point2, metadata))
            
            # Remove bidirectional connection
            del self.connections[point1][point2]
            del self.connections[point2][point1]
            
            # Clean up empty connection points
            if not self.connections[point1]:
                del self.connections[point1]
            if not self.connections[point2]:
                del self.connections[point2]
                
            # Remove metadata
            if (point1, point2) in self.connection_metadata:
                del self.connection_metadata[(point1, point2)]

class PatternCache:
    """Cache for frequently accessed geometric patterns"""
    def __init__(self, max_size=100):
        self.cache = {}
        self.max_size = max_size
        self.access_count = {}
        
    def get(self, key):
        if key in self.cache:
            self.access_count[key] += 1
            return self.cache[key]
        return None
        
    def put(self, key, value):
        if len(self.cache) >= self.max_size:
            # Remove least accessed item
            min_key = min(self.access_count.items(), key=lambda x: x[1])[0]
            del self.cache[min_key]
            del self.access_count[min_key]
            
        self.cache[key] = value
        self.access_count[key] = 1

class GeometryPoint(QGraphicsEllipseItem):
    """Interactive point item with number label."""
    def __init__(self, x, y, number, radius=5):
        super().__init__(-radius, -radius, radius*2, radius*2)
        self.number = number
        self.setPos(x, y)
        self.setup_appearance()
        self.setup_label()
        
    def setup_appearance(self):
        self.setFlag(QGraphicsItem.ItemIsSelectable)
        self.setBrush(QBrush(QColor("dodgerblue")))
        self.setPen(QPen(QColor("dodgerblue")))
        self.setZValue(10)  # Keep points above lines
        
    def setup_label(self):
        if self.scene():
            self.label = self.scene().addText(str(self.number))
            self.label.setDefaultTextColor(QColor("black"))
            self.update_label_position()
            
    def update_label_position(self):
        if hasattr(self, 'label') and self.label:
            pos = self.scenePos()
            self.label.setPos(pos.x() - 10, pos.y() - 25)

class GeometryLine(QGraphicsLineItem):
    class Type:
        BASE = 1    # Structural lines (polygon edges)
        PATTERN = 2 # Pattern lines (radial connections)
        CUSTOM = 3  # User-drawn lines

    def __init__(self, start_point, end_point, line_type):
        p1 = start_point.scenePos()
        p2 = end_point.scenePos()
        super().__init__(p1.x(), p1.y(), p2.x(), p2.y())
        self.start_point = start_point
        self.end_point = end_point
        self.line_type = line_type
        self.setup_appearance()
        
    def setup_appearance(self):
        self.setFlag(QGraphicsItem.ItemIsSelectable)
        if self.line_type == self.Type.BASE:
            self.setPen(QPen(QColor(70, 130, 180), 2))
        elif self.line_type == self.Type.PATTERN:
            self.setPen(QPen(QColor(255, 165, 0), 2))
        else:  # CUSTOM
            self.setPen(QPen(QColor(255, 165, 0), 4))
        self.setZValue(5)  # Above background, below points

class GeometryScene(QGraphicsScene):
    def __init__(self):
        super().__init__()
        self.last_clicked_point = None
        self.drawing_mode = True
        self.preview_line = None
        
    def create_centered_polygon(self, sides, layers, layer_distance=50):
        """Create a centered polygon pattern with given number of sides and layers"""
        # Create center point
        center = GeometryPoint(0, 0, 1)
        self.addItem(center)
        points = [center]
        
        point_number = 2
        
        # Create each layer
        for layer in range(1, layers + 1):
            layer_points = []
            
            # Create points for this layer
            for i in range(sides):
                angle = 2 * math.pi * i / sides
                x = layer * layer_distance * math.cos(angle)
                y = layer * layer_distance * math.sin(angle)
                
                point = GeometryPoint(x, y, point_number)
                self.addItem(point)
                layer_points.append(point)
                points.append(point)
                point_number += 1
            
            # Create polygon edges
            for i in range(sides):
                line = GeometryLine(
                    layer_points[i],
                    layer_points[(i + 1) % sides],
                    GeometryLine.Type.BASE
                )
                self.addItem(line)
            
            # Create radial connections to center
            for point in layer_points:
                line = GeometryLine(
                    center,
                    point,
                    GeometryLine.Type.PATTERN
                )
                self.addItem(line)
                
        return points

    def get_nearest_point(self, pos, max_distance=20):
        """Find nearest point to given position"""
        items = self.items(QRectF(
            pos.x() - max_distance,
            pos.y() - max_distance,
            max_distance * 2,
            max_distance * 2
        ))
        
        nearest = None
        min_dist = float('inf')
        
        for item in items:
            if isinstance(item, GeometryPoint):
                dist = (item.scenePos() - pos).manhattanLength()
                if dist < min_dist and dist <= max_distance:
                    min_dist = dist
                    nearest = item
                    
        return nearest

    def get_nearest_line(self, pos, max_distance=20):
        """Find nearest line to given position"""
        items = self.items(QRectF(
            pos.x() - max_distance,
            pos.y() - max_distance,
            max_distance * 2,
            max_distance * 2
        ))
        
        nearest = None
        min_dist = float('inf')
        
        for item in items:
            if isinstance(item, GeometryLine):
                dist = self.distance_to_line_segment(
                    pos,
                    item.line().p1(),
                    item.line().p2()
                )
                if dist < min_dist and dist <= max_distance:
                    min_dist = dist
                    nearest = item
                    
        return nearest